### ISSUE TITLE
How to remove new crosshair

### ISSUE THREAD

**Issue by huffulumpagus** [rbjaxter/budhud#100]
Hey, I've been using BudHud for like, forever. But this new crosshair, I just really don't like it. I thought if I selected a new one, It'd go away, but it didn't. So this is the only place I know to ask, could you just tell me how to disable it? It seems to override every other crosshair, so that you'll end up having 2 crosshairs and its really weird. Thanks in advance :)

**Comment by huffulumpagus** [comment]
Nevermind. I re-enabled transparent viewmodels and the crosshair went away on it's own

**Comment by rbjaxter** [comment]
Looks like I had accidentally enabled it in an update; it's fixed now. Thanks!

**Comment by TerminatorT800** [comment]
Yeah saw that aswell, just turned it off myself
