### ISSUE TITLE
Killstreak and other numbers overlapping.

### ISSUE THREAD

**Issue by PrestidigitationAKAMagic** [rbjaxter/budhud#108]
Resolution: 1680x1050
OS: 64-bit, x64-based processor

Snipers bazaar bargain heads and killstreaks overlap.
![koth_badlands0001](https://cloud.githubusercontent.com/assets/18595772/14710589/a231419a-07de-11e6-882e-9527d1ec3bc7.png)
![koth_harvest_final0001](https://cloud.githubusercontent.com/assets/18595772/14710615/c5dd35cc-07de-11e6-8123-992f045dddde.png)

**Comment by rbjaxter** [comment]
I'll look into this soon.

**Comment by rbjaxter** [comment]
Fixed, I'll close this when I push the commit. Thanks for the heads up :)
