### ISSUE TITLE
Timer Broken/Out of Place

### ISSUE THREAD

**Issue by TerminatorT800** [rbjaxter/budhud#109]
http://steamcommunity.com/sharedfiles/filedetails/?id=671211707

Out of place timer with textures being miss placed

Resolution - 1920 x 1080
Monitor Size - 1920 x 1080

**Comment by rbjaxter** [comment]
Looking into this now.

**Comment by rbjaxter** [comment]
[This is working on my end](http://i.imgur.com/zyW9tf4.jpg); I assume this was an issue that Valve fixed, but let me know if it's still happening.

**Comment by TerminatorT800** [comment]
Hm ok, I've been having this issue for server all months now thinking that you would be fixing it, but I guess it's my clients end then. I will test today or tomorrow and tell you

**Comment by TerminatorT800** [comment]
Nope still doesn't work. I'm not the only one have the issue I saw

**Comment by rbjaxter** [comment]
That's quite odd. Do you have any lingering folders in your \custom\ folder that could be overwriting the newer ones?

**Comment by TerminatorT800** [comment]
All I have currently in my custom folder is The most recent budhud file, and my custom scripts 
http://steamcommunity.com/groups/TermsTermi/discussions/0/492379439693395873/
There was a script to edited the default HUD, but I've removed that a long time ago.

**Comment by rbjaxter** [comment]
Huh.. what OS are you on?

**Comment by TerminatorT800** [comment]
Newest version of MacOSX

**Comment by rbjaxter** [comment]
Hey @TerminatorT800, sorry for being so slow on responding here. I'm going to go ahead and close this for now but it's still totally bothering me. If you're still having an issue with this, drop your Steam profile here and I'll add you to try and figure this out. I have some other Mac users with my hud, so it's odd to me that they're not sharing a similar issue.
