### ISSUE TITLE
Fix disappearing ammo

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#128]
May have to do with min mode being enabled.

**Comment by rbjaxter** [comment]
May not actually have to do with minmode. One person reporting it stated it happens on W10, can't imagine it's that though?

**Comment by TerminatorT800** [comment]
It's with Mac aswell, I could try testing with different settings they changed

**Comment by rbjaxter** [comment]
Okay, I can pretty much confirm it's due to having minmode on. I think I may move away from having minmode solely affect the scoreboard in order to open up other possibilities in the future. Not sure though.

**Comment by rbjaxter** [comment]
I nuked all _minmode entries in _tf2hud (Find in Files > replace all _minmode with something else) to fix this, in case anyone would like to fix it themselves now.  I'm likely going to wait until I have a large portion of the hud updated before actually committing any changes.
