### ISSUE TITLE
Mac hud issues

### ISSUE THREAD

**Issue by 808dkaneohe** [rbjaxter/budhud#131]
I recently did a full reinstall of budhud using the latest download from huds.tf and for some reason the hud partially works. Basically the loading screen is the normal blue gradient but the main menu remains unchanged, and the existing "Find a Match" dropdown does not function. Yet certain elements still work, the ammo numbers are colored and the custom spy disguise outline animation i use still works, but the rest is tf2 default hud. 
Thanks, and keep up the good work!

**Comment by rbjaxter** [comment]
I'm currently in the process of updating my hud. When I push all of those changes (hopefully within a week), would you mind testing it out again then? I just want to make sure I didn't incidentally fix it first. :D

**Comment by 808dkaneohe** [comment]
Okej np
