### ISSUE TITLE
Issue with favorite server buttons

### ISSUE THREAD

**Issue by 808dkaneohe** [rbjaxter/budhud#157]
I have set a server button to start a local server of tr_walkway, I have attatched the [gamemenu.res](http://pastebin.com/MpBizZKV) file here, let me know if you need another file. I get `Unknown command "engine"` in consle.
If it makes a difference I run a Mac and used [Atom](atom.io) to edit the files

Thanks, I love all the changes.

EDIT: It did work with the multiplayer MicSnobs button I made

**Comment by rbjaxter** [comment]
Heya!

Looks like you have "engine" twice; instead of `engine engine map tr_walkway_rc2`, set it to `engine map tr_walkway_rc2 and it should work. 

Let me know if you have any other issues :)

**Comment by 808dkaneohe** [comment]
oh...
*all around me are familiar faces...*

**Comment by rbjaxter** [comment]
happens to the best of us :D
