### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by newinthegame** [rbjaxter/budhud#165]
I am trying to replace budhud with another HUD and to do that I am trying to delete the budhud file. I am the administrator on my computer and when I try to delete it it says you require administrator permission to perform this action . I give the permission and then it says you require permission from ADMIN even after I have given permission. If try to delete every folder individually it says access denied.

Am I doing something wrong?

**Comment by rbjaxter** [comment]
Have you figured this out? I'm not sure what the issue could be, as the file itself shouldn't be denying you access from deleting it. If you're still having issues, I would try using the command prompt: https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/del.mspx?mfr=true

Obviously when using this method, you have to be careful, so if you're not familiar with command prompt you might want to read up on it or continue exploring other avenues

**Comment by newinthegame** [comment]
I did not find a way to fix this so the easy work around was to ditch that installation and reainstall tf2 in a different steam library folder. I will probably use the command prompt to delete when I get time as I am working on a graphic design project. Exploring other avenues would probably be a waste of time as using the command prompt would be a faster way of getting rid of it.
Thank you for taking time to reply to this , there are so many small scale applications that have virtually no support and it makes me happy to see someone who actually cares about their code. Your add on is pretty nifty and had gained popularity for good reason too. Good luck in keeping your coding up to date and thanks again.

**Comment by rbjaxter** [comment]
Thanks a ton! Sorry for such a slow response; my notification settings are all screwed up :(. If you happen to find a solution to this that can be fixed on my end, let me know.

Good luck on your project!
