### ISSUE TITLE
Extend scoreboard to show all players

### ISSUE THREAD

**Issue by ireperson** [rbjaxter/budhud#168]
Hey, noticed that the hud seems to cut off the scoreboard even when there are more players online than shown. Not sure if this is something that has to be disabled or an issue with the hud.

ty, ire

**Comment by rbjaxter** [comment]
ah sorry for the delay :(. This is caused by having minmode on, I believe. Try putting `cl_hud_minmode 0` in console.

**Comment by ireperson** [comment]
Thanks for the fix, scoreboard works now
ty
