### ISSUE TITLE
bh_chat_lowerleft.res customization gets disabled after disconnecting from a server

### ISSUE THREAD

**Issue by NikWillOrStuff** [rbjaxter/budhud#169]
took me a while to figure out why it would randomly work and not work, but it reliably breaks every time I connect to any server (matchmaking, community, self-hosted), disconnect to main menu, then connect to any server again.

**Comment by rbjaxter** [comment]
oddly enough, I actually don't have this problem when connecting to a local or community server. I believe this happens in casual/competitive due to animation lines that cause the chat to return to the top left. I'll try removing these, but I'm not sure if it'll fix this specific issue.
