### ISSUE TITLE
Huge Lag Spike after using the quick voice command (z,x,c)

### ISSUE THREAD

**Issue by bobby2128** [rbjaxter/budhud#178]
There are huge lag spike after using the quick voice command, which is z/x/c + number. There is none when using the default hud. I have also tried to disable the friend list in the menu.

**Comment by rbjaxter** [comment]
that's very strange; I've tried using them while using my hud and I don't have anything like that happen, so I'm not sure what to tell you. I'd try using a different hud and seeing if that still happens. that's honestly a very strange bug

**Comment by bobby2128** [comment]
I have use other hud but nothing similar seems to happen. :(
Here is a little video about what happen: https://www.youtube.com/watch?v=JLrV-JxbHkM
I am using traditional chinese as my language but changing it back to English will result in the same issue.

**Comment by bobby2128** [comment]
And also the name of other teammates don't seems to show

**Comment by bobby2128** [comment]
Oh! I see where the problem is. Apparently enable medic rainbow ubercharge will cause voice command to be lag, because it will enable bh_ubertracking.txt. The problem is fixed now. Sorry about that

**Comment by rbjaxter** [comment]
Glad you figured it out! I'm sorry about that. I'll remove that file so it doesn't happen again.
