### ISSUE TITLE
names when looking at players don't work

### ISSUE THREAD

**Issue by jepminer** [rbjaxter/budhud#191]
![20171113160240_1](https://user-images.githubusercontent.com/33632057/32735559-fa741ac4-c88c-11e7-837e-eac4e96274ee.jpg)
![20171113160613_1](https://user-images.githubusercontent.com/33632057/32735562-fcba57ee-c88c-11e7-88c7-9a93e916f250.jpg)
![20171113160616_1](https://user-images.githubusercontent.com/33632057/32735582-0a734706-c88d-11e7-9744-d8ff3a7299bb.jpg)
as seen in these screenshots names half show or don't show at all, this makes spy checking a real pain

**Comment by rbjaxter** [comment]
this should be fixed in the next update :). It's also available in the experimental branch.

The particular change that fixes this can be found here: https://github.com/rbjaxter/budhud/commit/58f4b87c948049ebb153a0440110f14605cacd35#diff-ef07aacad412ac45ed805dc8b992fa0f
