### ISSUE TITLE
Loading Screen Glitch

### ISSUE THREAD

**Issue by yaoghu** [rbjaxter/budhud#193]
Hey...
Im loving the hud so far...

just one slight bug...
im using gnu/linux btw...

problem is,the name of the map is displayed on top of my stats while loading....

![screenshot_20171211_180718](https://user-images.githubusercontent.com/29171250/33845910-f4076bd8-deca-11e7-91c8-167adc5c73ee.png)

other times,everything seems to be perfect...

![screenshot_20171211_184416](https://user-images.githubusercontent.com/29171250/33845931-05b05ce6-decb-11e7-9a03-96c19d7b3a31.png)

THANK U SOO MUCH FOR MAKING THIS HUD....
I HATE THE STOCK ONE!!

tried rays,toon.....but this is the one for me...

**Comment by rbjaxter** [comment]
This is honestly one of the weirder bugs I've seen. I've had it happen a few times to me but csnt consistently make it happen. I'll need to try and figure out what causes it. If you happen to figure out what does, let me know 

I'm glad you're liking the hud! :D

**Comment by yaoghu** [comment]
im not familiar with the hud creation process...but ill look into it...

thanks man.

**Comment by rbjaxter** [comment]
I'm going to go ahead and close this for now since I haven't encountered it in a while. I'll re-open it if it happens again.
