### ISSUE TITLE
Convert included config to mastercomfig

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#194]

**Comment by tcmal** [comment]
Mastercomfig has a whole bunch of customisable parts to it, really the graphics configs should just be removed, they're out of scope.

**Comment by rbjaxter** [comment]
Yeah, having looked into it a bit more myself I think they should probably be removed as well. I've always been hesitant to add things like this as it creates a new range of issues that could sprout up, and just in general I don't think it's the best idea to load configs in this manner. I think I'll go ahead and remove the configs in the next update.
