### ISSUE TITLE
Mann Co store glitch (?)

### ISSUE THREAD

**Issue by lucyusm15** [rbjaxter/budhud#196]
I can't click on the demoman items in the shop. Is it just me or anyone else have the same problem?
![20180105155910_1](https://user-images.githubusercontent.com/35133154/34602406-32f3dc58-f232-11e7-823e-f537c70cd3ab.jpg)

**Comment by rbjaxter** [comment]
hey!

This is happening to me as well -- I'll look into it. Thanks for reporting!

**Comment by rbjaxter** [comment]
Fixed on my end -- I'll push it in the next update. I had the "demo" entry listed as "demoman".

If you'd like to fix this yourself in the mean time:
1. Navigate to `\budhud\_budhud\resource\ui\econ\v2\storepage.res`
2. Scroll down until you see "demoman"
3. Change it to "demo"

**Comment by lucyusm15** [comment]
Thank you :D

**Comment by rbjaxter** [comment]
No problem! Bit of a random question, but I noticed your resolution is 1366 x 768 -- do you have any issues with the hud (things getting cut off, etc)? I haven't checked in a _long_ time to be frank, and I just want to double-check that it's still working fine on smaller resolutions.

**Comment by lucyusm15** [comment]
No, it's working fine in my resolution. Thank you once again. Sorry that i
don't  reply to the 2 previous messages, i rarely open up my gmail xD
