### ISSUE TITLE
Tf2 Budhud Not working

### ISSUE THREAD

**Issue by HkLuna** [rbjaxter/budhud#200]
I downloaded the git as a zip, and uncompressed the budhud folder on Custom,
![capture](https://user-images.githubusercontent.com/1467487/35781257-84ec368a-09c6-11e8-9e9a-4a1fa4e44de6.JPG)
but when i enter the game it looks like this
1) At first, it looks like its working fine
![20180204160945_1](https://user-images.githubusercontent.com/1467487/35781264-a0870654-09c6-11e8-9b16-951492b6c6d6.jpg)
2) Then you can clearly see its not
![20180204160949_1](https://user-images.githubusercontent.com/1467487/35781268-aef45020-09c6-11e8-880f-5df45d251ac8.jpg)
3) I Joined a private server just to check if it was just the Main Menu but nope
![20180204161051_1](https://user-images.githubusercontent.com/1467487/35781274-c2728ec8-09c6-11e8-9fd1-e8625335734f.jpg)

![20180204161058_1](https://user-images.githubusercontent.com/1467487/35781275-c602ae1a-09c6-11e8-9b44-a6a2a4c4f600.jpg)

Just For Clarification i used Budhud before, but i never had this problem
![20171227015645_1](https://user-images.githubusercontent.com/1467487/35781319-53c1de1a-09c7-11e8-9335-4ca6554bbd17.jpg)

Thanks In Advance

**Comment by rbjaxter** [comment]
I tried to reproduce what happened to you by removing my `info.vdf` file and it does appear that that was the issue. If you need further help fixing this, let me know!

**Comment by rbjaxter** [comment]
Should be fixed in #435b3e4

**Comment by HkLuna** [comment]
Just noticed you answered, il test it as soon as i get to my home and comment if it either fixes it or not

**Comment by HkLuna** [comment]
Moving Info.vdf inside the folder works, so i think this should be closed!
