### ISSUE TITLE
budhud not working anymore

### ISSUE THREAD

**Issue by Spacecookie92** [rbjaxter/budhud#217]
It was working fine last time I booted up, but now it's gone. Attempted reinstall but no luck, any suggestions?

**Comment by rbjaxter** [comment]
I'm not sure unfortunately, I haven't heard of anyone having issues loading it as of late :(. Maybe check the wiki again and follow it step by step just to verify? https://github.com/rbjaxter/budhud/wiki/Installation

**Comment by rbjaxter** [comment]
Are you still having issues? If so, feel free to re-open this and I'll try to help as best as I can!
