### ISSUE TITLE
Black lines on startup?

### ISSUE THREAD

**Issue by OctoNezd** [rbjaxter/budhud#258]
![image](https://user-images.githubusercontent.com/15308404/47264469-84e3ee00-d520-11e8-99e9-73a7cbfb0a67.png)
Opening and closing console fixes that.
Only modification applied is budhud
None of customizations are on
autoexec.cfg:
```
closecaption 1
exec bh_captions_competitive.cfg
viewmodel_fov 90
```
Running TF2 in windowed noborder at 1080p with DirectX 9.0

**Comment by rbjaxter** [comment]
Thanks for the info, let me test it on my end

**Comment by rbjaxter** [comment]
Tested with all of the same settings and I wasn't able to reproduce, unfortunately :(
https://i.imgur.com/6jiMK23.png

**Comment by OctoNezd** [comment]
Yep. Was running on insider 1809 - rolled back to RTM 1809 and the GeForce drivers that came with my laptop and the bug was gone
