### ISSUE TITLE
Improve casual menu appearance

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#261]

**Comment by dribbleondo** [comment]
The buttons for the top right need to be icons instead of arrows, It's quite confusing.

**Comment by rbjaxter** [comment]
I really don't think it's as confusing as you're making it out to be. People can always change it back themselves if they're struggling with it that much:
https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/matchmakingdashboard.res#L27
https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/matchmakingdashboard.res#L53
https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/matchmakingdashboard.res#L79
