### ISSUE TITLE
Engineer Pip-Boy Build menu not centered

### ISSUE THREAD

**Issue by Spacecoreflake** [rbjaxter/budhud#266]
![image](https://user-images.githubusercontent.com/9213561/48676267-a4445a00-eb64-11e8-85f6-6a9080aec7a8.png)

It seems to me that the Pip boy UI does not seem to be centered.

Cheers

**Comment by rbjaxter** [comment]
I'll tie this into #264 and try to fix this right now, thanks!

**Comment by rbjaxter** [comment]
![1y72ahr](https://user-images.githubusercontent.com/509599/48680043-f1680200-eb4b-11e8-8a7a-94f497b04e1f.jpg)
this good?

**Comment by Spacecoreflake** [comment]
Looks perfect! Thanks for the fast fix!
