### ISSUE TITLE
Building Status Display / 3D Class Model Location / Chat Box Coloring

### ISSUE THREAD

**Issue by MrKrunk** [rbjaxter/budhud#294]
- Add instructions to wiki on how to move engineer's building display (not metal counter) to original spot in default hud (top-left)

- Add instructions to wiki on how to move (rotate, raise, lower, etc.) 3D Class Model Display (I.E. next to health display)

- Add instructions to wiki on how to modify chat box colors/opacity

I have zero experience in coding and when I look at all the lines of code in stuff like this, I have no idea what I'm supposed to do. A lot of the things you can customize in budhud already have their own detailed instructions, and I appreciate that. Just need some other help in customizing other details is all.

**Comment by rbjaxter** [comment]
I added building display: https://github.com/rbjaxter/budhud/wiki/Building-Display
and updated https://github.com/rbjaxter/budhud/wiki/Player-Class-3D-Model

Let me know if they provide enough information.

The last one is honestly a mystery to me, as I never messed with the colors of the chatbox too much :D
I think it's mainly controlled in `\custom\budhud\resource\chatscheme.res` but I've only recently started to mess with it a bit.

**Comment by rbjaxter** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/509599/64903456-3a0a2200-d66e-11e9-9e77-90a744ac26e8.png). Believe I pushed it in an earlier commit.
