### ISSUE TITLE
"You're on your way to:" is on top of player stats

### ISSUE THREAD

**Issue by SupinePandora43** [rbjaxter/budhud#296]
how must look:
![](https://i.imgur.com/sFx3Qsk.png)
how it actually looks:
![image](https://user-images.githubusercontent.com/36124472/63238588-3e524380-c258-11e9-8ee2-cba6ab98f46a.png)

**Comment by rbjaxter** [comment]
This seems to happen very rarely for me as well. Generally speaking with huds, if something doesn't happen consistently/can't be reproduced consistently it tends to be a TF2 issue. I haven't been able to isolate this issue in all of my tests, so I think this may actually be the case.

Oddly, it happened a lot for a certain stretch of time, but now I haven't seen it happen again in a while :\

**Comment by SupinePandora43** [comment]
probably [this](https://steamcommunity.com/app/440/discussions/0/1697169163401623844/), can fix. i test it

**Comment by SupinePandora43** [comment]
[this](https://github.com/rbjaxter/budhud/issues/296#issuecomment-522293449) not work

**Comment by SupinePandora43** [comment]
###### image added

**Comment by SupinePandora43** [comment]
@rbjaxter when i trying to play in other gamemodes (something excluding cp_dustbowl), loading screen looks like it (1st image)

**Comment by rbjaxter** [comment]
Yeah, I'm fairly convinced this is a TF2 issue given how irregularly it happens. _Generally_ speaking that isn't a sign of a hud issue

**Comment by SupinePandora43** [comment]
somehow it fixed! stats appearing only while map name not showed up
