### ISSUE TITLE
problems with backpack on resolution 1280x1024

### ISSUE THREAD

**Issue by SupinePandora43** [rbjaxter/budhud#297]
problems with **BACK** button (for switching between pages)
![image](https://user-images.githubusercontent.com/36124472/63211615-9e3ad400-c10a-11e9-9746-c93bc75468db.png)
**back** button is showed, but only few pixels
also if i directly press on button it's not switch pages, biut if i press in invisible hitbox (bit to right) it's works!

**Comment by rbjaxter** [comment]
Thanks for reportign, I'll look into this

**Comment by rbjaxter** [comment]
This should be fixed in the next update, will update this when it's added; thanks for pointing it out!

**Comment by rbjaxter** [comment]
this should be fixed in the above commit; feel free to re-open this if you're still having issues :)

**Comment by SupinePandora43** [comment]
@rbjaxter don't work

**Comment by rbjaxter** [comment]
oh sorry, I didn't notice the arrows being cut off. I'll work on that

**Comment by SupinePandora43** [comment]
@rbjaxter i have question about whayay's crosshairs, so why they're outlined?! (it looks weird)

**Comment by rbjaxter** [comment]
you can remove the outline by using `CrosshairAA` instead of `CrosshairOL` in the `bh_crosshairs.res` entry for whayay's crosshairs

**Comment by SupinePandora43** [comment]
@rbjaxter 1280×1024 is 5:4

**Comment by rbjaxter** [comment]
![image](https://user-images.githubusercontent.com/509599/63238803-f8b45d00-c1fc-11e9-94f9-3efb0e7e7eea.png)
I believe it's fixed now, I'll push a change

**Comment by SupinePandora43** [comment]
@rbjaxter , i pulled it, ITS WORK!!! thanks for fixing!

can u add this installation guide to wiki?!:
1. navigate to `Team Fortress 2/tf/custom`
2. open console/terminal `Ctrl+RightMouseButton`
3. run `git clone https://github.com/rbjaxter/budhud.git`
to update:
1. navigate to `Team Fortress 2/tf/custom`
2. open console/terminal `Ctrl+RightMouseButton`
3. run `git pull`
