### ISSUE TITLE
Fix itempanel overlap with footer/header bar

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#306]
*might* be able to hide all bars but the one where it's drawn and then lower its z-value

**Comment by Bryophyllum** [comment]
Is that the issue in the screenshot below?

![overlap_held_item](https://user-images.githubusercontent.com/27376783/66704661-6624cb80-ed1e-11e9-9b86-8aeda55279d1.png)

**Comment by rbjaxter** [comment]
The overlap I'm thinking of is different from that, but it would be nice to also fix that. Those panels are really jank though, so I'm not sure how plausible it would be. I'll need to look into it a bit
