### ISSUE TITLE
Fix medals appearing in freezecams (casual)

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#307]

**Comment by rbjaxter** [comment]
I'm having some issues getting this to constantly reproduce; if anyone happens to record a demo that has the medal showing (or better yet, can use `vgui_drawtree 1` and figure out what the element is called), let me know!

**Comment by rbjaxter** [comment]
wiethoofd made a great observation that this might actually be the medals appearing from the winpanel, which would make a ton of sense. I sorta just assumed it was during killcams rofl. may have a fix for this which I'll try to test

**Comment by rbjaxter** [comment]
^ above isn't the case, it's actually related to killcams in some way

**Comment by rbjaxter** [comment]
https://steamuserimages-a.akamaihd.net/ugc/776244466259903087/D81E3DC94F076E780AFB6CB692A0D9FBAB812B9B/
https://steamuserimages-a.akamaihd.net/ugc/776244466259902389/7804183743AF789884CB85E8BE5B4E795334B502/

I ran in and died like 40 times and only got it to happen once, I'm not sure what prompts it.
![image](https://user-images.githubusercontent.com/509599/73995607-04602100-490e-11ea-906d-783950cd9297.png)

This is another instance of it happening from #321 
https://user-images.githubusercontent.com/38357837/73473531-3b25bc80-438d-11ea-8572-e47cf64eb481.png

**Comment by rbjaxter** [comment]
(this was indeed not the fix)

**Comment by Scoutman01** [comment]
For me it appear when i trigger the scorebard during the freezecams, maybe put medal_width to 0 may fix it ?

**Comment by rbjaxter** [comment]
#334 has a potential way to replicate the issue, will test

**Comment by rbjaxter** [comment]
Zetos stumbled on a screenshot of this happening in ToonHUD, which coooooould suggest it's a default hud issue

![https://steamuserimages-a.akamaihd.net/ugc/775110953440146890/8616217CB483635FECCAE005EACFD7C495923902/]

**Comment by rbjaxter** [comment]
Still happening as of this date and version of the hud.

**Comment by BingBongBonky** [comment]
I've tried it and I don't believe I have a demo recording of it but it seems to happen when you die and check the scoreboard and close it before the killcam is over. It takes the rank of the person you killed and that's what shows up in the top left.

**Comment by rbjaxter** [comment]
hmm, that's an interesting idea and would make sense that you can't catch it in a demo. I wonder if there's even anything I could do about that without hiding medals in the scoreboard altogether

**Comment by BingBongBonky** [comment]
My best guess as for why is that when you open the scoreboard other HUD elements are temporarily hidden so this may just be the game loading everything again and just trying to hide the medal the best it can. I would test it but I have no idea how to stop the hiding myself.

**Comment by Creeper2006** [comment]
![image](https://user-images.githubusercontent.com/64898415/125581669-bf5b1136-08b5-4801-9901-4fea4de9e7a7.png)

It doesn't seem to happen to me, though.

**Comment by Creeper2006** [comment]
![image](https://user-images.githubusercontent.com/64898415/125582780-36fc60c8-f813-41ff-a066-a74e993667d8.png)

Tried a few times and it seems I don't get it within immediate effect. Is it occasional?

**Comment by BingBongBonky** [comment]
It has to be the killcam. My best guess is they were originally going to show the casual badge in the killcam and then decided against it.

**Comment by rbjaxter** [comment]
I think it is actually the scoreboard somehow. Someone else in the huds.tf discord was having an issue with their scoreboard medals being squished together. Coincidentally they also had the top left medal issue, and it shows the top left medal being squished as well: 
![tt2](https://user-images.githubusercontent.com/509599/126552221-aed2c4ec-401a-4ea1-9493-f3e2a83753cd.png)

**Comment by rbjaxter** [comment]
I may have actually solved this by using a refract hidden in the top left on the scoreboard.res file. Not sure how it will look for <dx90 though, will need to check that (since refracts don't work properly on those)

**Comment by rbjaxter** [comment]
meh, it does work but it causes too many other issues
