### ISSUE TITLE
mvm broken

### ISSUE THREAD

**Issue by SupinePandora43** [rbjaxter/budhud#311]
![](https://steamuserimages-a.akamaihd.net/ugc/771730171997885322/0A56863DC47C808CF1E4EA220BF3632A16FB8CF8/?imw=1024&imh=819&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true)

###### also what's about recompile textures for mvm, but with NO LEVEL OF DETAIL?!

**Comment by rbjaxter** [comment]
Is this broken for you on the latest version of the hud? I don't have any issues on a resolution that is near to yours:
![image](https://user-images.githubusercontent.com/509599/68079526-5b52d900-fda8-11e9-9148-67ba40ce9e75.png)

**Comment by SupinePandora43** [comment]
@rbjaxter , OwO you returned!
that problem exist in lobby, in left top corner you can see, i not alone

**Comment by rbjaxter** [comment]
sorry for the delays, I haven't been working on my hud in a long time.

I've since tested this with/without someone in the party and can't replicate this unfortunately.
