### ISSUE TITLE
unpure.vpk warning message

### ISSUE THREAD

**Issue by SupinePandora43** [rbjaxter/budhud#312]
["Casual", "Competitive", "MvM", "Community servers"] must have message something like "Remove femme_pyro.vpk to safely play"
screenshot from default hud:
![image](https://user-images.githubusercontent.com/36124472/68102713-521f5480-feed-11e9-90e8-880f3fbdc928.png)

**Comment by blank-tf** [comment]
Remove femme_pyro.vpk from your custom folder? I don't see what the issue is here.

**Comment by SupinePandora43** [comment]
@blank-tf , it's not concept art. it's default hud unpure.vpk warning

**Comment by blank-tf** [comment]
Then remove the vpks causing the issue. I'm not sure why you're posting here.

**Comment by SupinePandora43** [comment]
@blank-tf , i post it here because budhud has no this, while default hud have

**Comment by blank-tf** [comment]
It is not needed. There is nothing unsafe about using vpks on valve servers.

**Comment by rbjaxter** [comment]
I can't believe I'm saying this, but I tried downloading a femme pyro vpk as you have shown in your screenshot to try and replicate this but I didn't get any errors trying to launch casual. 

I think this warning is safe to leave out from the hud, but if other people have similar issues and are able to link a VPK that would normally cause the messages to appear I'll look into it again.
