### ISSUE TITLE
Item skip dont work & Casual rank bug

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#321]
- When you get a new Item you have the message "Continue [E]", but the thing is when i press E nothing happends. I think its a problem from the HUD and not me but not really sure.

- After a death i see my Casual medal in the Left corner very tiny (maybe the problem from #307 already ).
![image](https://user-images.githubusercontent.com/38357837/73473531-3b25bc80-438d-11ea-8572-e47cf64eb481.png)

**Comment by rbjaxter** [comment]
heya!

For your first issue, I *believe* this is a TF2 issue but I haven't confirmed it yet: https://github.com/rbjaxter/budhud/wiki/Known-Issues#-unconfirmed-tf2-issues

If this ever happens to you, you should be able to hit Enter to "accept" the item. It's annoying, but I'm not sure what about the hud would cause it unfortunately (if it is the hud).

For your second issue, you're right that it's #307. I've been meaning to fix this for a while but every time I load into a casual game I forget to see what element is causing the issue. I need to record a demo and fix it up.

**Comment by rbjaxter** [comment]
Going to close this for now and keep putting any information I have on the medal bug in #307.
