### ISSUE TITLE
[BUG] Users background

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#330]
Hey again, since the last Update Today/Yeterday is something broken with the Backgrounds's. i dont have notice the Problem before and im sure it dont should looks like so.
(Left and Ride side)
![image](https://user-images.githubusercontent.com/38357837/83257674-25969700-a1b5-11ea-8d8a-9835a353eb12.png)

**Comment by rbjaxter** [comment]
Thanks for pointing this out. Should be a fairly easy fix, I believe [this file](https://github.com/rbjaxter/budhud/blob/master/%23users/dane_/%23customization/bh_mainmenu_gif.res) needs to be renamed from `bh_mainmenu_gif` to `bh_menu_gif`

**Comment by rbjaxter** [comment]
Actually, it appears to be a different issue; I'll have to look into it more

**Comment by rbjaxter** [comment]
hmm, I don't appear to be having this issue:
![image](https://user-images.githubusercontent.com/509599/83306722-f46b9600-a1b7-11ea-8bc6-4b0ece25c48d.png)

**Comment by rbjaxter** [comment]
If you wanted to, you could try downloading the development version of the hud and seeing if you have the same issue: https://github.com/rbjaxter/budhud/tree/development

**Comment by barbiehunter** [comment]
No i dont have the Issue by the development version, works fine.
![image](https://user-images.githubusercontent.com/38357837/83308273-c3ff1880-a206-11ea-9434-3ff83bac09e5.png)

**Comment by barbiehunter** [comment]
Looks like you Fixed it now, downloaded the newest master version and everything is fine. I close the Issue
![image](https://user-images.githubusercontent.com/38357837/83409491-cdf66680-a414-11ea-89dd-9fd248971826.png)
