### ISSUE TITLE
[BUG] (Dane) Crosshair

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#338]
Hey, after the new Updates i had see there is something wrong with the Crosshair.  It Looks Like 2 Crosshairs in one.
New one: 
![image](https://user-images.githubusercontent.com/38357837/86476133-3bfcb900-bd46-11ea-92d9-a81ff8ae9e5f.png)

Old One:
![image](https://user-images.githubusercontent.com/38357837/86476160-49b23e80-bd46-11ea-8388-1c75e0cfe507.png)

**Comment by rbjaxter** [comment]
fixed in https://github.com/rbjaxter/budhud/commit/29ea910d506afdb59ccce79ca99991ebf9a16fcd, thank you! :)
