### ISSUE TITLE
Issue with main menu

### ISSUE THREAD

**Issue by Maelcat** [rbjaxter/budhud#341]
is there a way i can fix the #bh_
![image](https://user-images.githubusercontent.com/53267697/87466782-7daa2100-c5dc-11ea-960a-0955c07cc49c.png)

**Comment by Maelcat** [comment]
it also happens in the backpack, and can't press Q to exit
![image](https://user-images.githubusercontent.com/53267697/87468417-383b2300-c5df-11ea-84dd-185b75b56f2b.png)

**Comment by rbjaxter** [comment]
thanks for reporting; two other people have also reported having this issue as well today, but I can't replicate the issue. I'll keep looking into this

**Comment by rbjaxter** [comment]
Just checking, do you have TF2 set to a language other than english?

**Comment by Maelcat** [comment]
nope its english

**Comment by Maelcat** [comment]
side note
i just deleted my full custom folder, and verified the integrity of the game files
reinstalled the hud and now its somehow fixed

**Comment by rbjaxter** [comment]
it appears this has to do with tf2_bot_detector (https://github.com/PazerOP/tf2_bot_detector). I'm talking to pazer about it and will figure out what needs to happen to resolve the issue

**Comment by rbjaxter** [comment]
I'm getting reports from the others experiencing this issue that updating to the latest release of tf2_bot_detector (https://github.com/PazerOP/tf2_bot_detector/releases/tag/1.0.0.43) is fixing this issue; if you try this and it doesn't work for you still, let me know :)
