### ISSUE TITLE
Certain unicode characters are smaller than they should be.

### ISSUE THREAD

**Issue by Angalexik** [rbjaxter/budhud#345]
Screenshot:
![Screenshot](https://user-images.githubusercontent.com/58977805/90278289-7c804400-de67-11ea-9b0b-35e7afcf7d4a.png)

**Comment by rbjaxter** [comment]
Out of curiosity, have you tried installing the font? Oddly I've never had issues where someone needed to install a font to resolve an issue, but it's just another minor thing you could try if you haven't. The font's located in `budhud/resource/fonts/font-lato-semibold.ttf` (it may also be called `Lato-Semibold.ttf`)

I'm asking around to see if anyone knows of any solutions

**Comment by rbjaxter** [comment]
closing this for now, feel free to re-open if more information surfaces
