### ISSUE TITLE
Medigun names streamer hud

### ISSUE THREAD

**Issue by Scoutman01** [rbjaxter/budhud#348]
You can do the same thing that Hypnotize did, but the downside is that you have to add it in chat_english.txt so it completely remove the medigun name even if the streamer hud is disabled:

`//MEDIGUN NAMES`
`"TF_playerid_mediccharge_wpn"		"ÜberCharge: %s1%"`

**Comment by rbjaxter** [comment]
Yeah, since it does affect the default hud and can't be added as a #base include, that's why I decided not to take the chat tokens approach with it. It is a nice option for those looking to get rid of them to be aware of, though
