### ISSUE TITLE
Figure out a not-terrible way to document `#users/custom` usage

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#360]
In practice, customizing budhud by using the `#users/custom` folder would mean that you could update the entire budhud files (beyond just the `_tf2hud` files) while maintaining your customizations without issue.

It should be as easy as copying over a file you want to edit from the `_budhud` folder into `#users/custom`, and then making any changes. There are some caveats to this, though, as copying over _every_ aspect of the file means that the entire file remains unaffected by future changes, since the entire file is overwriting its `_budhud` equivalent. Gets kinda confusing fast.

**Comment by SupinePandora43** [comment]
I use `git pull` to update hud
