### ISSUE TITLE
"Find a Game" Menu not changing after renaming/deleting mainmenuoveride.res

### ISSUE THREAD

**Issue by jumper-cable-morty** [rbjaxter/budhud#375]
I've been trying to get the Find a Game menu back to default, and I thought following the page in the wiki or editing the files mentioned there would help, but after renaming and deleting them it didn't change it. In fact, everything else was back to default except that menu.

**Comment by rbjaxter** [comment]
That specific top bar is controlled by `matchmakingdashboard.res` in `..\budhud\_budhud\resource\ui`; renaming or deleting that should do the trick for you.

I'll update that wiki to include a few more of the files that I missed. Let me know if you have any other questions!

**Comment by rbjaxter** [comment]
Ah, I see the wiki includes `matchmakingdashboard.res` already, so you may be referring to the casual criteria/playlist UI. Let me track down those files and I'll post back once I get it all working

**Comment by rbjaxter** [comment]
I've managed to return it to this state, which seems to be the majority of the main menu:
![image](https://user-images.githubusercontent.com/509599/103363508-1986f680-4a70-11eb-992c-5ed7baebd3e8.png)

I moved the following files into a folder called `temp` (you can delete or rename them all as well, your choice) to get this result:
![image](https://user-images.githubusercontent.com/509599/103363619-636fdc80-4a70-11eb-8dff-29135f9a8ba6.png)

**Comment by jumper-cable-morty** [comment]
That's what I was looking for! Thanks, I really appreciate it!
