### ISSUE TITLE
[BUG] HP on other player & question

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#380]
It no longer shows the HP of players when aimed at them & what is the gray dash at the top.
![image](https://user-images.githubusercontent.com/38357837/114302572-e372fd00-9ac9-11eb-8587-c66c364204d1.png)

**Comment by rbjaxter** [comment]
this should be fixed in this commit, thanks for pointing it out! https://github.com/rbjaxter/budhud/commit/627a4978d2f58b4aefe9786c4413cefc9928eceb
