### ISSUE TITLE
[Bug] Disguise Name & Health info

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#382]
When you disguise as a Spy, the name is displayed above the HP as you see on the screenshot.

![image](https://user-images.githubusercontent.com/38357837/115032025-21589280-9ec9-11eb-8a26-ecfe9c5b05eb.png)

**Comment by rbjaxter** [comment]
^ fixed with that commit, ty! 

fix is just one line so it'll be easy for anyone to fix who wants to
