### ISSUE TITLE
[BUG] Button on Box opening

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#383]
The button for opening a box is not fully recognized when you move the mouse over it. (Video as an example).
https://user-images.githubusercontent.com/38357837/115620832-f8376800-a2f5-11eb-92f2-e9fb8cd009fe.mp4

**Comment by rbjaxter** [comment]
I did what I could with this, but I believe I'd have to unbox an item every time I wanted to check the updated positioning. It's going to look bad, but it'll have to do for now I suppose
