### ISSUE TITLE
[Improve] Chat box

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#388]
The chat box where you write is a bit too small as seen in the video, the "_" is not visible. I know it is not so important, just have seen the problem only until here.
https://user-images.githubusercontent.com/38357837/116057176-d421b100-a67e-11eb-9a86-647f46f1494b.mp4

**Comment by rbjaxter** [comment]
I don't really think there's much that I can do as far as editing the chat box goes. At best, you could probably make the font size used smaller but I'm going to stick to keeping its current readability, since this currently only really affects underscores
