### ISSUE TITLE
[BUG, Linux] missing characters in "healing ..." panel

### ISSUE THREAD

**Issue by SupinePandora43** [rbjaxter/budhud#395]
# Default HUD

![image](https://user-images.githubusercontent.com/36124472/123535965-044e0480-d741-11eb-9005-6b6e2b84da32.png)

# budhud

![image](https://user-images.githubusercontent.com/36124472/123536349-41b39180-d743-11eb-9899-901adec922a7.png)

**Comment by rbjaxter** [comment]
Is your `budhud/resource/clientscheme/bh_fontentries.res` file up to date? It should look like this: https://github.com/rbjaxter/budhud/blob/master/resource/clientscheme/bh_fontentries.res

If it is, could you try going into `budhud/resource` and doing the following:
- Delete/rename `chat_english.txt` to something else
- Rename `chat_russian.txt` to `chat_english.txt`
- Restart Team Fortress 2 and see if this issue persists

The missing character is a consequence of the new hud font replacing certain characters (including spaces) with question marks. This is primarily to deal with bots having hidden characters in their names. 

To my understanding, setting the range as it is set in `bh_fontentries.res` should result in spaces using the fall-back font, which would mean this shouldn't be happening if your `bh_fontentries.res` file was up to date.

**Comment by SupinePandora43** [comment]
> Is your ... file up to date?

I update my hud using `git pull` command, and it shows that everything up to date.

> This is primarily to deal with bots having hidden characters in their names.
Then. I saw it working (bots with my nick were having those question icons)

**Comment by rbjaxter** [comment]
Did you have any luck renaming the chat_russian file?

**Comment by rbjaxter** [comment]
I've reverted the changes that cause this to happen, more hassle than it's worth.

Updating to the latest version of the hud should fix this issue. If you still have issues after updating, you may need to reinstall the budhud font (Lato). 

It can be found here: `..\custom\budhud\resource\fonts\font-latosemibold-original.ttf`
