### ISSUE TITLE
Crosshair override

### ISSUE THREAD

**Issue by Creeper2006** [rbjaxter/budhud#402]
The crosshair built in with budhud won't disappear. (I experimented by removing the crosshair related files in #customize. Didn't work, so I put them back in. Is there any way to remove the built-in crosshair?

**Comment by rbjaxter** [comment]
this is an error on my part (#401); go into `budhud/#users/` and change the folder `whisker` to `whisker_`

**Comment by Creeper2006** [comment]
Thanks! It works just fine now. If I want to, where can I re-enable it? (Without it overriding the other crosshairs)
