### ISSUE TITLE
Crosshair bugged

### ISSUE THREAD

**Issue by Katzenwerfer** [rbjaxter/budhud#403]
One of the custom crosshairs is always overlaid, even if you haven't enabled it
I can't pinpoint which commit made the issue appear, but it happens in the most recent version of the repo prior to this post

**Comment by rbjaxter** [comment]
this should be fixed by this commit I believe: https://github.com/rbjaxter/budhud/commit/0d9e1b1acd85dd0360aaf15a88a8b2d149da96f1

**Comment by Katzenwerfer** [comment]
it is, thanks
