### ISSUE TITLE
Health over target is wrong when targetID health cross is enabled 

### ISSUE THREAD

**Issue by evelyndooley** [rbjaxter/budhud#410]
With bh_targetid_healthcross1 (and 2).res in my enabled customization folder, the health number displayed above a teammate is wrong. It looks like the last number is cut off.

![image](https://user-images.githubusercontent.com/31457788/132442320-697a70ca-36a3-4df9-b188-21df0ce29e6a.png)

**Comment by rbjaxter** [comment]
this should be fixed by the added file in https://github.com/rbjaxter/budhud/commit/be13a615f1841f01044365035d57dd86ccabcb3a now; let me know if you still run into issues. thanks for reporting :)
