### ISSUE TITLE
Some overlap in streamer mode on MvM scoreboard

### ISSUE THREAD

**Issue by BingBongBonky** [rbjaxter/budhud#413]
![image](https://user-images.githubusercontent.com/73761963/134069453-8754e3a9-8cc2-4fb7-9d31-0c5ef6a14248.png)
I'll see if I can solve the issue and make a PR

**Comment by BingBongBonky** [comment]
I suck

**Comment by rbjaxter** [comment]
Ooo good catch, didn't think to check that. No worries if you can't solve/PR, I can fix it if not. Just let me know. ty for pointing this out :D

**Comment by rbjaxter** [comment]
fixing this up now, will close it with the commit once I get it all sorted
