### ISSUE TITLE
Spy Disguise Menu Stuck in Top Left?

### ISSUE THREAD

**Issue by SirLuigi5528** [rbjaxter/budhud#415]
I heard how good this hud was and decided to use it but when I played Spy, the disguise menu was stuck in the top left unlike being stuck in the middle where it always is. Now I have heard some people say it is because I prefer to play TF2 with a controller but that would make no sense since literally every hud never has had this issue before.

Below is a screenshot I took to show my issue:
![20211102103643_2](https://user-images.githubusercontent.com/75645478/139869494-75000f44-8830-4f8f-b66c-5d4e7faee5c6.jpg)

I hope this helps, if you need anymore info that I did not list, please let me know.

**Comment by SirLuigi5528** [comment]
I can try to see if it works, is this a command I put in the files somewhere or do I use the console ingame? Thanks for responding.

**Comment by rbjaxter** [comment]
may or may not be kinda fixed based on the above commit, not sure. I still have no way to easily test with a controller

**Comment by SirLuigi5528** [comment]
I can try to use the hud again to see if it fixed

**Comment by SirLuigi5528** [comment]
Okay yeah I am seeing the new menu for engineer and spy, the only issue is unlike with the controller menus, these have no indication of what building I am picking/destroying or what class im disguising as. 
![image](https://user-images.githubusercontent.com/75645478/167285048-698319a4-1411-48a7-9abc-f7907c9a900a.png)
Example being this outline of the Sentry Gun
![image](https://user-images.githubusercontent.com/75645478/167285073-403579d8-2618-4023-9755-2e7dc4ac1cd3.png)
and the outline of the class you disguise as.

Hope this maybe helps!

**Comment by rbjaxter** [comment]
Yeah, that's the part I was worried about. Hmm... I need to do some more digging around on how to get a virtual controller running on my PC. If I could just see the same console UI you're seeing it'd be much easier to fix, haha.

**Comment by rbjaxter** [comment]
I decided to mess with this a bit more, I think I've made some good progress:
![NVIDIA_Share_VMrz7rHVzm](https://user-images.githubusercontent.com/509599/176978334-37c98fea-2c5e-4cf0-8df6-f56e5a5d921b.gif)
![NVIDIA_Share_zwbFZB7EkC](https://user-images.githubusercontent.com/509599/176978423-085b4458-a459-4ba5-b289-d207322d11b5.gif)
(program that finally made this easy to test was reWASD, though it's a paid program so I'm just using a trial)

@SirLuigi5528 Do you happen to know of anything else that is broken with a controller? I saw a stream using budhud with a controller (koyotemoone), maybe have been an older version of the hud but it seemed like the taunt UI as well as the respawn screen were a bit strange (showing bars at top/bottom, etc).

**Comment by rbjaxter** [comment]
I also uhh...can't figure out how to open the destroy UI? lmao

**Comment by SirLuigi5528** [comment]
I'd have to check to see, but I will make sure. Great to see you are doing well with the controller menus. Thats why I have been stuck with toonhud since others huds dont factor controllers. As for destroy UI, there isnts a destroy menu, its left trigger to destroy unlike where you have to open a separate menu to destroy buildings

**Comment by SirLuigi5528** [comment]
Alright, using the hud the build and disguise menus are in the middle with the build menu having the outline of what you're building but I still don't see the outline for the disguise (unless you are still working on that since I saw it on the examples you showed). Other than that, the only thing I wasn't sure about was with the vaccinator as I don't know if the resistance indicator is supposed to be there
Example: 
![image](https://user-images.githubusercontent.com/75645478/176979524-d9baf69c-2625-456e-b04d-b1929397ac20.png)
Again other than that, it is much more controller accessible!

**Comment by rbjaxter** [comment]
Yeah, that's where the shield should be displayed. Glad to hear it's coming across passably on your end too :)

The taunt menu seems okay too? I may need to look at the eureka effect too actually...heck

**Comment by SirLuigi5528** [comment]
Oh you're right! Lemme check that real quick for you! I almost forgot!

**Comment by SirLuigi5528** [comment]
Okay just checked and yeah you were right about the eureka effect, I completely overlooked it. No indicators or image for exit teleporter.
Eureka Effect Menu:
![image](https://user-images.githubusercontent.com/75645478/176979769-35fe34c1-d73c-4c83-98ed-d93d986f3ae2.png)
As for the taunt menu, they never really did indicators for taunts so I always just used the taunt menu like everyone else except opening it with the X button on controller
Taunt Menu:
![image](https://user-images.githubusercontent.com/75645478/176979803-be1c892a-ed58-4d7c-897d-18a40d5c9fac.png)

Again, it's great to have you listen to feedback even from me who plays TF2 on controller lol. I get a lot of hate for playing with controller in TF2.

**Comment by rbjaxter** [comment]
Thank you for finding all of that. And of course, it's my pleasure :D. I never know how many people use certain features or play under certain conditions (controller, etc) so I'd like to cover as many as I can. I was just unfortunately having a lot of troubles getting the controller elements to display to work on them.

I'll try to see what I can do with those to get it all touched up

**Comment by SirLuigi5528** [comment]
I see. I know nothing about hud development so I didn't think it was much trouble to try and make a hud accessible to controller players but it's nice to hear you want to cover center conditions of how people play TF2. If I could, I would want to help other hud developers find issues with their huds with controller compatibility but it's hard since usually some huds don't have good github pages. If you need me to check anything else, I can check. Again, thanks!

**Comment by rbjaxter** [comment]
It's a bit tricky with my hud just because there's a lot of #base shenanigans going on. You effectively have to have twice the amount of engineer files to account for 360 and non-360 (triple if you want to support steam controller too). 

the tricky part is more so figuring out how to use #base in such a way that you only have to change a few files to change the entire appearance. how I'm doing it at the moment means that, if I change the non-360 UI in the future, it'll also update the 360 UI version. simply copying the files over and editing both 360 and non-360 files at the same time would be doable, but a pain if it ever actually came to it.

here's some progress on the build UI. I wasn't too sure whether or not I should keep the buttons, but I also improved the quality of them (because they look horrible on lower graphics quality)
![hl2_HbA0rVEa9U](https://user-images.githubusercontent.com/509599/176980540-14cd1dbb-8add-4a72-a9d9-b94398036ca8.gif)
:

**Comment by SirLuigi5528** [comment]
Wow, I see. I guess thats why hud devs usually skip over the controller ui. It would make sense. I would say keep the buttons since it helps players know what buttons do what like in the disguise menu how Y swaps the team to disguise as.

**Comment by rbjaxter** [comment]
![hl2_wmlnTdsbFI](https://user-images.githubusercontent.com/509599/176980827-b17b47f2-f5d5-46a7-863a-1afb831fa032.gif)

Spy done as well now. Just left aligned the buttons because I imagine those playing on other languages will have issues with it being centered anyways.

**Comment by SirLuigi5528** [comment]
Wow, it looks great!

**Comment by rbjaxter** [comment]
Looking into the default files a bit more, I don't think there...actually is an "active background" box for the Eureka effect, as well as the taunt menu hahaha, so I guess this may be sufficient for now. I'll upload the changes shortly but keep this open, as I'm sure I'm missing something somewhere...it'll also give an idea of how many changes this required hahaha

**Comment by SirLuigi5528** [comment]
Weird, I wonder why they don't have active backgrounds. Maybe there's a way to fix that but again I don't know since I am not gifted in hud development. Glad to be of some help looking for hud issues with controller for you! Maybe I should help other hud devs with finding these issues if they want to make their huds controller friendly. If you ever need me to check anything else in the hud, let me know!

**Comment by rbjaxter** [comment]
I'll be sure to let you know :). honestly this issue with your screenshots is probably a good reference for other hud developers, since they'll need to emulate a controller anyways to get proper positioning/etc

**Comment by SirLuigi5528** [comment]
Well if you know any hud developers with huds that want to make them controller friendly, I can totally download their hud and check everything we have before that needs fixing and screenshot the menus and uis to show them. Ill be sure to update my budhud to see if everything works.

**Comment by SirLuigi5528** [comment]
Okay went to check the update to the hud. Build menu is perfect but the disguise menu is for some reason still missing its indicator. I did see the buttons for team disguise and selecting the disguise. Other than that one issue, its great!
![image](https://user-images.githubusercontent.com/75645478/176982355-4fe83336-ddbb-4037-b630-781c1de1f82f.png)

**Comment by rbjaxter** [comment]
strange, I think the visibility was getting mucked up a bit, hopefully the spy UI is fixed now

**Comment by SirLuigi5528** [comment]
Let me check it out real quick for you.

**Comment by SirLuigi5528** [comment]
Yep, it is fixed now! 
![image](https://user-images.githubusercontent.com/75645478/176982853-a9d77571-c768-46bc-96b4-1944dc5e74c5.png)
The only thing is the Eureka Effect menu but I don't use that weapon much at all so it's not a huge issue atm. I do have a question though, is there a way to move the chat to its default position since budhud puts it in the upper left?

**Comment by rbjaxter** [comment]
In `budhud/#customization/` there's a file called `bh_chat_lowerleft.res` that you can move into the `_enabled` folder, it should be pretty near the default chat location

**Comment by SirLuigi5528** [comment]
Oh wow, that's really simple to customize unlike other huds where I have to mess with a notepad. Thanks again for all the help and I hope you can figure out that Eureka Effect active background problem! :D

**Comment by rbjaxter** [comment]
As far as I can tell, the Eureka Effect is the same as the taunt menu; it doesn't actually have a selector like the others do.

What is weird is that the person I've seen use a controller with budhud had xbox buttons appearing in their taunt menu, but I can't get that to happen on my end, and I don't see anything in the file for it. Quite strange

**Comment by rbjaxter** [comment]
Actually, they may have combined 360 and steam controller versions of that element into just `hudmenutauntselection_sc.res`, so I may need to mess with that more. But yeah, it shows the taunt menu as you show it, not as I saw it in a stream. Let me see if I can get a screenshot of how it appeared in a stream of someone using their taunt menu

**Comment by rbjaxter** [comment]
![image](https://user-images.githubusercontent.com/509599/177021207-3bfae83b-e400-4248-862a-f0615083833e.png)

Looking at their engineer build UI, they may actually be using a Steam Controller. Which would mean they added support to the taunt menu for the Steam controller but not an Xbox controller...which also means I need to add support for steam controllers 🙃

**Comment by rbjaxter** [comment]
I have no way to emulate a Steam Controller nor do I own one myself, so I can't fix this for now
