### ISSUE TITLE
[BUG] Specate button

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#418]
I found out that the "Spectate" button in the scoreboard does not work or doesn't do anything.

Video (its a to big file for github): https://streamable.com/enjho2
PS: Shit Autobalance too, i hate it xD

**Comment by rbjaxter** [comment]
this would be an issue within tf2 unfortunately, we don't really have any control over the actual buttons used there. for whatever reason, the scoreboard mouse2 option has always been a bit jank

**Comment by barbiehunter** [comment]
Ouh okay, wollte es zur sicherheit reporten, aber gut zu wissen.

**Comment by rbjaxter** [comment]
I appreciate you reporting it all the same :). it is certainly a bit of a toss up on whether or not something will be a hud issue or tf2 issue at times, haha :)
