### ISSUE TITLE
MvM wave info overlapping (and underlapping) progress bar

### ISSUE THREAD

**Issue by Gyarik** [rbjaxter/budhud#421]
![image](https://user-images.githubusercontent.com/40033289/156921353-4b99f661-7fc5-4d5e-bf16-25d6ce281ac2.png)

As the image above shows, wave info both overlaps and underlaps the progress bar. Is it fixable?

**Comment by rbjaxter** [comment]
this may be due to having minmode enabled (for some reason). probably a tf2 issue, since if it was a hud issue all icons would be above or below the health bar

try setting `cl_hud_minmode` to `0`

**Comment by Gyarik** [comment]
That seems to solve the issue, thanks. What does minmode effectively change though?

**Comment by rbjaxter** [comment]
I believe technically it shouldn't be changing anything, because I have it entirely disabled in the default hud files and don't leverage it at all in my hud. so I'd guess this mvm wave UI is somehow hardcoded or something
