### ISSUE TITLE
Update chat_ files

### ISSUE THREAD

**Issue by Tiagoquix** [rbjaxter/budhud#422]
Some of the existing chat files are no longer supported by TF2, like chat_arabic.txt for example.

I suggest that the files be updated with the latest version of the JarateKing's script.

https://github.com/JarateKing/BaseHud/blob/master/resource/chat_update_all_to_english.bat

**Comment by rbjaxter** [comment]
I just took a look at the TF2 store page to see what languages they list as officially supported and adjusted it accordingly. I believe it's more or less the same as JarateKing's latest list.

**Comment by rbjaxter** [comment]
cleaned this up in https://github.com/rbjaxter/budhud/commit/36f43b9b8b12e8f38c50877b98ace82f6b281cc1
