### ISSUE TITLE
[BUG] Name at spectate

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#429]
Hey Jason,

Since one of the last Team Fortress 2 update, the name has been moved when spectating people in general. As in the picture below, it is now always very far to the left (I use the config from Dane).

![hl2_o3dQyuMSY7](https://user-images.githubusercontent.com/38357837/178152456-0f7410e9-81ea-4f2b-bcd1-f164468fe253.jpg)

**Comment by rbjaxter** [comment]
Interesting, I haven't seen this behavior on my end. is this in casual or does it apply to all gamemodes?

**Comment by barbiehunter** [comment]
> 



> Interesting, I haven't seen this behavior on my end. is this in casual or does it apply to all gamemodes?

I have the problem in every game mode, no matter if casual, community server or against bots offline

**Comment by rbjaxter** [comment]
I'm going to close this and #426 for now, as I haven't been able to replicate either and haven't heard any reports of either happening from anyone else yet. I may re-open them if I do, but until then my only advice would be to try and get a fresh copy of budhud from the GitHub and see if the problem persists.

**Comment by rbjaxter** [comment]
hey @barbiehunter, just wanted to check:
![image](https://user-images.githubusercontent.com/509599/200699315-0c71af42-4596-4f8f-9b4f-583b720d90bb.png)

I didn't personally know this option existed in advanced options, is there a chance yours is not set to default? Just wanted to see if that was perhaps the problem
