### ISSUE TITLE
can i **submit** a users folder?

### ISSUE THREAD

**Issue by NukeThief** [rbjaxter/budhud#432]
thats the question

**Comment by rbjaxter** [comment]
Typically for the `#users` folders, I keep them to YouTubers / Twitch personalities / etc who will have a wide audience making use of them. This is primarily to avoid bloating up the HUD too much (oddly enough I think like >60% of the size of the hud comes from custom #users backgrounds lol). I would do it for more people, but I'd have to add #users lines for everyone which wouldn't be too ideal.

With that said, for personal edits you may actually have better luck forking the hud from here and then making your changes that way. You'd have to learn Git (if you weren't already familiar with it), but it would allow you to basically pull in any new changes I make and then compare them to your files so you can keep your specific customizations.

Another alternative that I forgot about until now: there is actually a `#base` line in all of the files for a `#users/custom` folder that is unused at the moment. So, technically if you wanted to take the `#base` approach, you could make a folder in `#users` called `custom` and make your changes in that folder. That may actually end up being trickier depending on what your knowledge level for both is, though.
