### ISSUE TITLE
Crosshair might be off-center

### ISSUE THREAD

**Issue by NukeThief** [rbjaxter/budhud#433]
Why do i think that? Well i use a combination of yellow crosshair : and tf2s ingame green dot crosshair and i see some bits of the dot from the : crosshair and i figured out there there is a pos offset on it but idk where to change it.

**Comment by rbjaxter** [comment]
Unfortunately with how font crosshairs work, there's no way to make them all perfectly centered.

It depends on what crosshair you're trying to use, but for the included one you'd adjust the xpos and ypos values here: https://github.com/rbjaxter/budhud/blob/master/%23customization/_enabled/bh_crosshairs.res#L27-L28

you'd basically adjust these values by one, `hud_reloadscheme`, see if it's good, and then repeat until it is. change `0.4999` to `0.4998`, then `0.4997`, and so on
