### ISSUE TITLE
[BUG?] Alert shortcuts at main menu not working

### ISSUE THREAD

**Issue by Malgreen** [rbjaxter/budhud#434]
## The Issue
The shortcuts (E & Q) when looking at _alerts_ do not work when at main menu.
I don't know how to fix this, as this is normally tied to the actual buttons themselves, so this might be an unfixable 'bug', due to the way Valve has structured the hud files/functionality.

## Reproduce
To reproduce, look at a new alert at the main menu, and try using the shortcuts.

**Comment by rbjaxter** [comment]
I'm a bit confused where you're trying to use Q and E on the menu. By alerts, do you mean item accept alerts (where it shows the item itself and it takes up the whole screen) or the "new item alert" that appears in the top middle while you're on the main menu?

I'm trying to recall if there were any buttons on the main menu that use Q and E to navigate, unless you mean while inside the backpack UI or something similar.

**Comment by Malgreen** [comment]
Yes, I'm talking about the item accept where it fills the whole screen - shortcuts work when looking at it in a match, but not on main menu

**Comment by rbjaxter** [comment]
Ahhh, yeah unfortunately I've actually never had any luck in getting them to work there. Tbh, I don't even remember them working in-game. I've tried a few different things to make it so you could scroll through items with A/D but to no avail, so I think it's just a limitation of TF2 (unless you know of other huds that make it work)

**Comment by Malgreen** [comment]
Nope, haven't been able to make it work either. I also believe it's just a TF2 limitation, I'm going to mess around with it a bit and create a new issue if I find a solution
