### ISSUE TITLE
Does budhud support linux (Ubuntu 22.04)?

### ISSUE THREAD

**Issue by vahvero** [rbjaxter/budhud#440]
I tried to follow the instructions given with unzip and managed to get following file structure:

```sh
~/.steam/steam/steamapps/common/Team Fortress 2/custom/budhud-master$ ls 
 _budhud               cfg              '#dev'      materials   scripts    _tf2hud
'budhud Updater.ps1'  '#customization'   info.vdf   resource    _stream_  '#users'
```

However, when I attempt to launch the game, I do not get any custom HUD for TF2. Is this just an issue with linux (Ubuntu 22.04) or am I missing a installation step?

**Comment by sheybey** [comment]
you're missing a directory there. the custom directory is under the game's search path `tf`, so the path needs to be `~/.steam/steam/steamapps/common/Team Fortress 2/tf/custom/budhud-master`

**Comment by vahvero** [comment]
Okey, after digging around the source files, correct path to extract these files is ```~/.steam/steam/steamapps/common/Team Fortress 2/tf/custom$ pwd
/home/vahvero/.steam/steam/steamapps/common/Team Fortress 2/tf/custom
``` not the windows path
