### ISSUE TITLE
Wrong option specified in the wiki related to setting building display position for engi

### ISSUE THREAD

**Issue by szero** [rbjaxter/budhud#451]
This [wiki](https://github.com/rbjaxter/budhud/wiki/Building-Display) says to modify `bh_BuildNav` in order to set the build menu position but the correct value name to change is `bh_BuildPin`.

**Comment by rbjaxter** [comment]
ahh yes, I changed `Nav` to `Pin` everywhere in the hud files to be consistent, but missed this on the wiki. good catch, thanks for pointing it out!
