### ISSUE TITLE
Medigun names show up when streamer mode is active and player is being healed

### ISSUE THREAD

**Issue by rx149** [rbjaxter/budhud#452]
See title: Medigun names show in the overlay that pops up when one is getting healed by a Medic.

**Comment by rbjaxter** [comment]
This is a known issue, but unfortunately I'm not really able to fix it because nuking names would also nuke things like the level of engineer buildings when you look at them, as well as just being able to tell what medigun someone is using in general (since they're all tied to the same element)

**Comment by rbjaxter** [comment]
Just checked to make sure and it appears I left a comment about it in the file it applies to: https://github.com/rbjaxter/budhud/blob/master/_stream_/resource/ui/targetid.res#L8-L18

That said, if you don't care about those names being missing you can always uncomment this section, and then it will also remove those medigun names
