### ISSUE TITLE
hl2.exe not found??

### ISSUE THREAD

**Issue by YayLolz** [rbjaxter/budhud#460]
I can't install the HUD apparently due to this bug, not sure how to fix after reading everything.

![image](https://github.com/rbjaxter/budhud/assets/67490116/042251f6-c14f-40e4-a8cc-403d4961bdba)

**Comment by lihuelworks** [comment]
For everyone who may be as dumb as me...make sure budhud folder is inside` C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\custom\budhud` before running the script, since the check is not done on an absolute path (i.e is checked ../hl2.exe instead of the whole path)

**Comment by rbjaxter** [comment]
Ah yeah, I should improve the wording of that error message. I haven't messed with the script in a while, but it is expecting the folder to be located in the correct spot at the moment
