### ISSUE TITLE
Request: Add font fixes for Linux players

### ISSUE THREAD

**Issue by kir68k** [rbjaxter/budhud#462]
Hi, I was wondering if it would be possible to implement a different chat font for linux users? Something like done in https://blog.lightwo.net/source-engine-font-fixes-linux.html. Unfortunately the CJK fix that uses depends on Microsoft fonts, but there should be a workaround.

I currently got the game to use Noto Sans + wqy-zenhei for CJK, although Noto Sans doesn't fix characters like ~ or italic unicode being used in steam usernames. If I type "~" into the chat it works, but steam usernames seem not to, also in the console.
![image](https://github.com/rbjaxter/budhud/assets/104025732/4b3171cd-b8f6-4328-86b5-4ff47ba00a8e)

I'm not sure if this can be done through the hud, sorry if this is an invalid issue!

**Comment by kir68k** [comment]
Seems like the "italic unicode" I was speaking of is in the "Mathematical Alphanumeric Symbols" block, going by fileformat.info not many fonts support it, but steam, Firefox, and android do it well... Really not sure which font would fix this, and seems too much of a niche case for this repo to fix, although I won't close this yet if CJK can be fixed.

**Comment by rbjaxter** [comment]
I'll be honest, anything this in-depth with linux + font compatibility is definitely out of my depth, so I'm not sure there's really anything I can do to contribute sadly. Even if I could, the percentage of people on linux is just so low that it's hard to justify me putting time into figuring it all out. not being able to quickly/easily test it is also another factor sadly :(

**Comment by kir68k** [comment]
I could learn a bit more how huds and budhud work to try and figure it out this weekend, maybe. Completely understand though considering it's a big minority group
