### ISSUE TITLE
bh_menu_defaultbackground does not work

### ISSUE THREAD

**Issue by MikeSesketcharba** [rbjaxter/budhud#464]
I moved the folder to _enabled and the default gif is still there. I also tried complementing it with bh_menu_hidegif but I get the default blue background instead of the vanilla tf2 backgrounds.

**Comment by MikeSesketcharba** [comment]
I should not I had to download from the source code instead of the releases page, since the bh_menu_defaultbackground was not in the releases version

**Comment by rbjaxter** [comment]
Yeah, it looks like it was already in the latest from the source code. It wouldn't have been in the releases because I added it shortly after the latest release. I'm going to update the release today, however if you tried the source code zip it should be working from that

**Comment by MikeSesketcharba** [comment]
Downloaded from source again. It works.
Now this is a perfect hud, thank you :)
