### ISSUE TITLE
find a better spot for the speedometer

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#473]

**Comment by TechnoSL** [comment]
i think a good suggestion would be somewhere under health/ammo (so you can still see it easily) or a wiki page giving instructions on how to move the speedometer wherever the user wishes

**Comment by rbjaxter** [comment]
yeah true, I think I was pretty focused on it being in the center of the screen but i really dont think its possible lmao:
![hl2_nVXZHWWnjQ](https://github.com/rbjaxter/budhud/assets/509599/3dea18b2-af87-4e71-b085-44692c2ff799)

**Comment by rbjaxter** [comment]
though now the issue is it overlaps with the buffed health, and offsetting it right or left of it feels weird

![hl2_BC8mD68CNd](https://github.com/rbjaxter/budhud/assets/509599/6aafd708-0dac-4e68-9b21-8a4cfb3ec6a1)

**Comment by rbjaxter** [comment]
it below ammo kinda suffers from there being ammonoclip (sniper/heavy/pyro) vs everything else with reserve

**Comment by rbjaxter** [comment]
I may have been able to squeeze it in above damage done and above the jump map timer by pushing the timer into the control points area. may have issues on community servers that also use hint display, not sure
