### ISSUE TITLE
Sometimes the default background breaks

### ISSUE THREAD

**Issue by MikeSesketcharba** [rbjaxter/budhud#475]
I have the defaults backgrounds enabled, with the bh_menu_defaultbackground in #enabled. It worked perfectly fine, but sometimes I get the default blue background. My guess is that between the rotation of default backgrounds, some files are missing so it displays the blue one instead.

Have been having this issue for a while but I have been procrastinating the issue report lol

**Comment by rbjaxter** [comment]
Heya, thanks for making the issue :D I appreciate it

I think I might know what's happening, and it's more of an oversight on my part. You are correct though, the default TF2 hud cycles through four different map backgrounds. Most HUDs hijack one of these included names (background_upward for instance), which is what budhud does as well. The customization doesn't actually remove the budhud background, so you basically have a 1 in 4 chance of getting it.

https://github.com/rbjaxter/budhud/commit/57a5af45d745ec2ea9bd61abee664aa3387b9f22
I haven't tested it extensively yet to be sure, but what I've done is just rename the budhud background and updated the chapterbackgrounds.txt file so it doesn't use one of those 4 backgrounds in the default rotation. On your end, you could either make these changes yourself and see if it continues to happen, or you could just go into `budhud/materials/console` and just delete the two VTF background files outright. Should have the same effect

**Comment by MikeSesketcharba** [comment]
Cool! I'm going to try it out. Thanks :) <3

**Comment by MikeSesketcharba** [comment]
Works now

**Comment by rbjaxter** [comment]
Sweet, glad it's working! Hopefully I didn't break something else in the
process 😎
