### ISSUE TITLE
Mann Up Victory Screen is Invisible

### ISSUE THREAD

**Issue by AndrewJackerryJacked** [rbjaxter/budhud#478]
All you can see is the sound effects that show up when you get items, but nothing else.

**Comment by rbjaxter** [comment]
Does this happen every single time or did it happen only on your first mvm game? I think this may honestly be a TF2 or an "affects all huds" issue unfortunately

**Comment by AndrewJackerryJacked** [comment]
This happened for four games I played.

**Comment by rbjaxter** [comment]
Hmm, strange. Are you on the latest version of budhud? Did this happen before, or just start happening?

If you're on a version of budhud that's older than April 14th 2024, I would suggest going into `budhud/resource/ui` and renaming or deleting `mvmvictorycontainer.res`, then seeing if it continues to happen. I added a fallback button to the victory container, so I'm curious if that's for some reason breaking things. Previously I didn't change the default files at all

**Comment by AndrewJackerryJacked** [comment]
Hey, I just realized I didn't have the most up to date version, mine is from back in April. I'm gonna play another game at some point and I'll let you what happens. If it dosen't work again I can send a screenshot.

**Comment by rbjaxter** [comment]
No worries. I honestly haven't really touched much of the MvM stuff since before April unfortunately, so I'm not too sure what the issue could be. It may just be a TF2 issue unfortunately. The only thing I added in the April update was actually a fallback button on that victory screen, so if it doesn't correctly show you'll at least have a way to get out of the UI

**Comment by AndrewJackerryJacked** [comment]
So I tried out two games, one where I renamed mvmvictorycontainer.res and both times it still wouldn't show properly
![20240504193941_1](https://github.com/rbjaxter/budhud/assets/31216626/39d13b85-1aeb-47e6-b1a9-a7b38b2562dc)
![20240504193946_1](https://github.com/rbjaxter/budhud/assets/31216626/4cb1cbb1-a5f3-4f72-ad99-f1d4f07c4cce)

**Comment by rbjaxter** [comment]
Hmmm interesting. It sucks that this is such a hard thing to troubleshoot lmao. I'm also curious if the tournament panels and engineer UI overlap in the default hud. I have to imagine they do, but I wonder if I can make that less sucky somehow

**Comment by rbjaxter** [comment]
The next time you play mvm, once you load into the mission can you do `hud_reloadscheme` in console, and then see if anything appears at the end? obviously don't go out of your way to do a mission now ofc

**Comment by rbjaxter** [comment]
The part that's especially strange to me is that nothing at all is appearing, which may mean it's outside of my control. Typically you should at least see a "CLOSE" button present

**Comment by rbjaxter** [comment]
oh...oh no....I see at least one substantial problem lmaoooo. why this was happening in your version pre-april, I don't know..but try this first:
1. go to budhud/resource/ui/mvmvictorycontainer.res
2. remove the extra ".res" entries at the end of each line

It should look like this:
![Code_khjuuPppyS](https://github.com/rbjaxter/budhud/assets/509599/bcadd3fd-ac19-46f5-8b8e-8d9c63268586)
not this:
![k4C5UskevT](https://github.com/rbjaxter/budhud/assets/509599/b307a1a9-31a3-42b1-826e-b692278a4ba2)

this could certaiiinlyyy be it

**Comment by rbjaxter** [comment]
If that does happen to be the problem, this is the commit that fixes it: https://github.com/rbjaxter/budhud/commit/0cd1a9d98e5501b1f68b7f3f13bb58c9c36843ad

I also moved the banner down a bit to not overlap with the match status at the top

**Comment by F1restar4** [comment]
This does appear to be fixed on 4c3beb5

**Comment by rbjaxter** [comment]
@F1restar4 Did you mean to reply to #479 or were you talking about the MvM victory screen? That last commit was for the other open issue. Either way, I'm glad something's fixed hahahah

**Comment by F1restar4** [comment]
@rbjaxter the mvm victory screen, I referenced that commit because it's the version I tested, even though the two shouldn't relate at all it seemed proper

**Comment by rbjaxter** [comment]
Ahh I see, that's great then. I'll close this for now, but if there seems to be further problems let me know. 

Besides my change that broke it, I wonder if they fixed the mvm victory screen breaking the first game with the 64 bit update, or some past patching update. Will be interesting to see if anyone else has further issues
