### ISSUE TITLE
[BUG] Invalid Health at Death

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#479]
I installed the latest version via github code (not release) and noticed that the dead (tested at Uncletopia) has the "Invalid" image in the Health bar. Happens too when you Look at a Teammate and when he dies seeing for a Moment the 
Extra Info: using the "users" Profile of Uncle Dane

![image](https://github.com/rbjaxter/budhud/assets/38357837/967a82a6-955d-48f7-b480-bca8542db35b)
![image](https://github.com/rbjaxter/budhud/assets/38357837/ae16df2e-ec4d-4681-b98b-5f5f1463b3e6)
![image](https://github.com/rbjaxter/budhud/assets/38357837/3555d45c-8918-49f5-9f7a-9e323fc562b5)

**Comment by rbjaxter** [comment]
Good catch, you can try doing the one change in this commit and see if it still happens. I'm not sure why your first two screenshots are happening, but I guess we'll see if it fixes those too
https://github.com/rbjaxter/budhud/commit/4c3beb581d6dd3c2d7759daacdc56639a9056568

**Comment by barbiehunter** [comment]
I gave it a try and its fixed in someway, but not 100%.  Before it seems to be Transparent if somebody dies, now its like a grey color

How was before;
![image](https://github.com/rbjaxter/budhud/assets/38357837/3b826cb9-c4c8-4c97-86e6-92e427b71f6b)
![image](https://github.com/rbjaxter/budhud/assets/38357837/1f1d3d9f-eaaa-4e65-ba61-fab03273182f)


How it looks with the Fix:
![image](https://github.com/rbjaxter/budhud/assets/38357837/507b26a1-97f0-4a82-9624-33539228473f)
![image](https://github.com/rbjaxter/budhud/assets/38357837/1d551f27-0434-42dd-9f0d-000835be1390)

**Comment by rbjaxter** [comment]
Okay, I think I'm understanding now. This element is treated differently in casual and community servers due to pure restrictions, so tbh I couldn't remember exactly what it looked like. If it's supposed to look transparent, you can go into `budhud/materials/hud` and change `"$color"` to `"{000 000 000 000}":
![Code_yPp1QmUCTj](https://github.com/rbjaxter/budhud/assets/509599/8b6a79fe-5bb5-4084-87fa-95fc327dd2e5)

**Comment by barbiehunter** [comment]
> you can go into `budhud/materials/hud/health_dead` and change `"$color"` to `"{000 000 000 000}"`:

This just seems to make it black 😅 Works fine with the current "releases" build on github which is like transparent. Tried it with 255 255 255 255 for normal transparency too, but it does not fix it either. My guess it have something to do with https://github.com/rbjaxter/budhud/commit/387e5ffa9a3f67692eed1a9e4586c00efd88250f but 100% sure

![image](https://github.com/rbjaxter/budhud/assets/38357837/78e1042f-c7c7-4b9f-ab2b-ede0e71357eb)

![image](https://github.com/rbjaxter/budhud/assets/38357837/aec35f77-713d-49f6-82ff-c47de613e634)

**Comment by rbjaxter** [comment]
Hmm, I'll have to take a look when I get home. I assumed you could set the
transparency of a solid VTF color, but perhaps you need an actual
transparent VTF.

That commit wouldn't be related, it just has to do with how I consolidated
some files

**Comment by rbjaxter** [comment]
@sumdudinhell you may honestly be onto something, I think changing `health_dead.vmt` to just this does fix it:
```
"UnlitGeneric"
{
    "$no_draw"                                                      "1"
}
```

I was out of town so I had forgotten about this and exactly how it used to look before lmao, but does this look right @barbiehunter?

enemy almost dead:
![image](https://github.com/rbjaxter/budhud/assets/509599/0721ec4a-eb22-4fe3-ae2c-911fced32409)

enemy death:
![image](https://github.com/rbjaxter/budhud/assets/509599/a5a0cc39-451c-4a45-871c-ebdd73ce23ec)

![image](https://github.com/rbjaxter/budhud/assets/509599/e689643e-343c-4e5a-aba4-6a49d212df21)

**Comment by rbjaxter** [comment]
dang, was hoping there was a chance this somehow made it sv pure friendly too but it doesn't, still stretched death icons in casual 😭

**Comment by barbiehunter** [comment]
> I was out of town so I had forgotten about this and exactly how it used to look before lmao, but does this look right @barbiehunter?

Yeah it was like that, but  yeah sad does not really work for Casual 😢

**Comment by rbjaxter** [comment]
yeah, nothing can be done about that unfortunately, it was the same in casual before as well. I'll push a commit eventually(tm) but in the mean time the above fix is pretty quick
