### ISSUE TITLE
Outdated file names on wiki page `Custom Menu Background`

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#480]
It seems that the file names on the wiki page [Custom Menu Background](https://github.com/rbjaxter/budhud/wiki/Custom-Menu-Background) haven't been updated to align with the changes made in https://github.com/rbjaxter/budhud/commit/57a5af45d745ec2ea9bd61abee664aa3387b9f22.

**Comment by rbjaxter** [comment]
Ah yeah, good catch. I believe I've updated it everywhere in there, though I wouldn't put it past me to miss something. Thanks for pointing it out :)
