### ISSUE TITLE
Inconsistencies with various panels/menus

### ISSUE THREAD

**Issue by Kruphixx** [rbjaxter/budhud#493]
Already talked about it on the budhud discord but I figured I'd post it here as well for some better visibility, I guess.

Several of the dialogs in the game are inconsistent, mainly talking about the border and background. Some screenshots below:

![20240630134848_1](https://github.com/rbjaxter/budhud/assets/50501742/a6d17918-e3cb-4dd9-b6a7-548adfa48cb1)

![20240630134855_1](https://github.com/rbjaxter/budhud/assets/50501742/dd32cb68-8e15-402a-bc81-a44c9a44d13d)

![20240630134923_1](https://github.com/rbjaxter/budhud/assets/50501742/10c53ea4-13d2-4e8d-968a-f8f1763fd242)

![20240630134946_1](https://github.com/rbjaxter/budhud/assets/50501742/7da7b198-440c-4977-bab0-642a000c31f9)

![20240630135114_1](https://github.com/rbjaxter/budhud/assets/50501742/01643f1a-8fc5-480d-b9cb-849cca88aca1)

**Comment by rbjaxter** [comment]
Training and Advanced Options have been fixed, however not much else can be done with the quit UI or vote menus from my my understanding

![image](https://github.com/rbjaxter/budhud/assets/509599/7d774d29-d2c9-49ad-8b02-351944343631)
![image](https://github.com/rbjaxter/budhud/assets/509599/575cb085-f21c-4b47-8ab7-769359e3a24e)
