### ISSUE TITLE
 Improve support for setup via `#users/custom`

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#499]
Some suggestions that I think you might find reasonable:

1. Move `#base` statement directing to `#users/custom` to the top in `scripts/hudlayout.res` and `resource/ui/econ/backpackpanel.res`.
2. Add `"file" "#users/custom/scripts/hudanimations_custom.txt"` to `scripts/hudanimations_manifest.txt`.
3. Add `#base` (and `file`) statements directing to `#users/custom/#customization/_enabled/` files to the appropriate files.

Essentially, I suggest the changes presented in the commit 16ecc56.

**Comment by rbjaxter** [comment]
This all seems pretty reasonable to me. I can manually add these at a later time, but if you'd alternatively like to make a PR with those changes I'd gladly accept it :)

**Comment by qkeitoe** [comment]
Yeah, sure. I'll make a PR in a couple hours.

**Comment by rbjaxter** [comment]
Now merged, thanks again!
