### ISSUE TITLE
Suggestions regarding item effect meters

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#502]
Here are some improvements regarding item effect meters that I think are more or less reasonable.

1. Make the shield charge label visible. I think it's especially important if a shield is equipped along with loose cannon:
    - Before:
    ![Screenshot (67)](https://github.com/rbjaxter/budhud/assets/66339491/b13f14e5-4140-4b68-8053-6a2f5ee43ddb)
    - After:
    ![Screenshot (68)](https://github.com/rbjaxter/budhud/assets/66339491/5732fd2c-baec-41a1-b8f6-d8cbbde90044)
2. Add a dedicated scheme color for a foreground color of the demoman charge meter. I've noticed that some competitive demoman players prefer to have this color set to yellow. 
https://github.com/rbjaxter/budhud/blob/3bc2760cc8a6fed8d990afa64e407eec6eae8217/_budhud/resource/ui/huddemomancharge.res#L11

**Comment by rbjaxter** [comment]
The first one I'd be reluctant to implement as a standard. I'm more preferential to the look of the bars without text and have never really run into issues myself with it (things like shield + loose cannon/etc, though admittedly I have a lot more hours than most and am used to it). However, I could probably add a customization to enable the labels for all meters fairly easily for those who want it.

My only trepidation with the second suggestion is that I'd want the process of coloring to be in line with how the other item meters are colored, which would mean with a refract. Truthfully i haven't touched that file in what feels like centuries, and I should probably have it #base to the other itemeffectmeter files like the rest of them so I may change it to behave like that. That'd also allow it to be colored by the same refract bars, as well.

**Comment by qkeitoe** [comment]
I see. I guess because I change HUDs quite often, I'm always more comfortable having bars with text. Or I just like the way it looks. :)

As I can see, `bh_ColoredMeter` colors not only the foreground but also the background of meters. However, for demoman charge meter It's possible to control the foreground and background colors independently.

**Comment by rbjaxter** [comment]
Yeah, I do know it's possible but I think it'd be weird to have a color for just that one meter tbh. If that wasn't the case I'd include it of course, but otherwise I'd probably end up doing the refract instead
