### ISSUE TITLE
Fix for `bh_targetid_healthcross/HealthIconPanel` 

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#503]
The issue itself:
![Screenshot (69)](https://github.com/rbjaxter/budhud/assets/66339491/79f7d925-5565-4c71-a1b5-bf84cebfd4b6)

It can be fixed like this 0fb9219:
![Screenshot (71)](https://github.com/rbjaxter/budhud/assets/66339491/339bd974-149a-436b-8df5-ae371191e72b)

Since it's quite painful to test, I'm not sure if `"tall" "20"` is the best choice, so I opened an issue, not a PR. :)

**Comment by rbjaxter** [comment]
That seems like a reasonable fix. And yeah, those health crosses are pretty cursed to work with sometimes so I'll just go with your values since it seems to work lmao 
![image](https://github.com/user-attachments/assets/e57887ec-28af-4c11-a071-7e59ff4b165a)
