### ISSUE TITLE
Overlapping Elements in Player Destruction Game Mode

### ISSUE THREAD

**Issue by PeanutKarver** [rbjaxter/budhud#522]
During the "Waiting for Players" period on Player Destruction Maps, the `_budhud` folder [hudmatchstatus.res](https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/hudmatchstatus.res) `ObjectiveStatusTimePanel` element, [hudobjectivetimepanel.res](https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/hudobjectivetimepanel.res) `WaitingForPlayersLabel` element, and the [hudobjectiveplayerdestruction.res](https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/hudobjectiveplayerdestruction.res) `CountdownContainer` element overlap with each other.

![20240729200028_1](https://github.com/user-attachments/assets/df71051f-2080-48a1-9e91-ec38dac5211d)

It's fine during the round.

![20240729200057_1](https://github.com/user-attachments/assets/d4c8055d-baa1-42d0-a60a-1368c2d8facc)

During Player Destruction rounds, the `_tf2hud` folder [hudobjectiveplayerdestruction.res](https://github.com/rbjaxter/budhud/blob/master/_tf2hud/resource/ui/hudobjectiveplayerdestruction.res) `CarriedContainer` element overlaps with the `_budhud` folder [disguisestatuspanel.res](https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/disguisestatuspanel.res) `bh_DisguisePin` element.

![20240729200548_1](https://github.com/user-attachments/assets/e25833f1-f90d-4947-9d19-986b80fb57f8)

Should be a simple fix. I just don't know how you'd want the elements to reposition.

If you want to, maybe consider adding the `CarriedContainer` element into the `_budhud` folder [hudobjectiveplayerdestruction.res](https://github.com/rbjaxter/budhud/blob/master/_tf2hud/resource/ui/hudobjectiveplayerdestruction.res) and edit it to look like budhud's MVM money counters. I don't know if it's possible to make it look exactly like the counter in MVM. It's just that in the default HUD, they look very similar. Of course, you don't have to do this. There are other avenues to making it fit the budhud style, and it's not like its current design isn't already functional.

![Player Destruction Count](https://github.com/user-attachments/assets/389f9dce-26f0-4e93-a600-09af862aab55)
![MVM Money](https://github.com/user-attachments/assets/454793a7-f6b8-423d-9960-52a85374ba6a)

**Comment by rbjaxter** [comment]
Yeahhh I had a feeling it would overlap with something like that when I moved it back lmao. What I may do is just remove the background and then move it down below where the "respawn time" message appears. I think I'd need to remove the background just because it's going to have to move so far down that it might become a distraction.

For the other thing you pointed out, I'll take a look and see what I can do.

**Comment by rbjaxter** [comment]
![image](https://github.com/user-attachments/assets/a522d234-d5fb-48df-9eb8-348e9f374813)
![image](https://github.com/user-attachments/assets/3ea86ca9-344b-482b-9839-10980bc6b4f5)

not the hugest fan but i honestly may just stick with doing this lmao. I don't really like the alternatives

**Comment by qkeitoe** [comment]
Couldn't the image next to the number be made a bit smaller? I think it would look better that way.

**Comment by rbjaxter** [comment]
![image](https://github.com/user-attachments/assets/c6adbb55-f68d-43c4-8b03-194e3111b8fe)
I could shrink it up a bit, or move it down there. Although shrinking it overall would probably be better
