### ISSUE TITLE
HUD elements that should show on death are not showing

### ISSUE THREAD

**Issue by Icharaimes** [rbjaxter/budhud#527]
As of the lastest updates to the hud, elements such as the name and remaining health of the person that killed you along with the weapon they used no longer show up when you die.

![no_elements](https://github.com/user-attachments/assets/506965f3-2212-46fe-9abd-1406b37fd0a5)

The elements appearing in a previous version:

![with_elements](https://github.com/user-attachments/assets/38776464-41a9-4fb9-9faa-6303ef8d0f7f)

**Comment by rbjaxter** [comment]
Strange, I didn't see this happening in my testing...I'll take another look. Likely has to do with this: https://github.com/rbjaxter/budhud/commit/df4c4b4471460b8c8954201fbc9e78133be872e0

**Comment by Icharaimes** [comment]
Just tested removing the additions in the mentioned file and that did fix it.

**Comment by rbjaxter** [comment]
I think I'll just revert it back to how it was before. Thanks for reporting it so quickly! :)
