### ISSUE TITLE
Key uncrating TitleLabel misaligned

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#531]
https://github.com/rbjaxter/budhud/blob/master/_budhud/resource/ui/econ/confirmapplydecodedialog.res

Needs tall value set to SOMETHING

**Comment by qkeitoe** [comment]
The issue seems to persist even after b2deb0e (I assume the set tall values are not big enough).
<img src="https://github.com/user-attachments/assets/ce30d1a1-f881-4166-99a1-de52e33ad792" width="50%" height="50%">

**Comment by rbjaxter** [comment]
yeah, for some reason I decided to add the fix to every element but that one. but in theory you just need to add a
```
    "TitleLabel"
    {
        "wide"                                                      "150"
    }
```

to `confirmapplydecodedialog.res`
