### ISSUE TITLE
Mission briefings do not word wrap.

### ISSUE THREAD

**Issue by Radial36** [rbjaxter/budhud#537]
Issue is at it says, mission briefings do not word wrap.
Stock VS Budhud:
![tf_win64_b5KHzq90c6](https://github.com/user-attachments/assets/d4dfeb89-9046-4bf2-bbd7-14a4b338aa44)
![tf_win64_XxED4vGL3K](https://github.com/user-attachments/assets/e2618d6d-c422-4643-9eb5-959753c14ff4)

Mission Briefing file itself:
[ctf_tour_b5_english.txt](https://github.com/user-attachments/files/17335452/ctf_tour_b5_english.txt)

**Comment by rbjaxter** [comment]
I can't find this map online, in servers, or in the casual browser. am i going crazy?

**Comment by Radial36** [comment]
That's because it's not added officially not hosted on any servers yet, I just linked it because it's the map I first noticed this happening on when getting it tested.

**Comment by rbjaxter** [comment]
I'd need a map with the same objective explanation text to be able to fix it myself, because this doesn't happen on any other map that I've seen yet

**Comment by Radial36** [comment]
I'll keep looking for more maps this happens on, but heres the map itself for now:
https://tf2maps.net/downloads/tour.18064/

**Comment by rbjaxter** [comment]
Perfect thank you! Was having a hard time finding the map, I'll check it out

**Comment by rbjaxter** [comment]
pretty easy fix, though I don't know if there are unintended consequences
![image](https://github.com/user-attachments/assets/df14fe52-75be-42cf-8a89-71faf01a2702)

just a matter of going into `budhud/_budhud/resource/ui/mapinfomenu.res` and changing `MapInfoText` values:
![image](https://github.com/user-attachments/assets/4b764902-b193-47d0-85b8-3338d2aba614)

I lowered the wide a bit, not even sure the xpos matters here. Will commit it after a few more tests
