### ISSUE TITLE
Outburst: UI elements overlapping/misaligned

### ISSUE THREAD

**Issue by Sizzler48** [rbjaxter/budhud#542]
![image](https://github.com/user-attachments/assets/0feaced9-273e-4d23-ad0c-b14f6d7080ab)

"No respawning" and Saxton's health overlap, and the health icon + total damage done at bottom.

**Comment by Sizzler48** [comment]
Using Linux Mint 22 as the OS.

**Comment by rbjaxter** [comment]
Should be fixed now with the above commit, let me know if you still run into issues. I did remove the hale background/border around the health. I like how it looks, though I'm not completely opposed to having it

**Comment by Sizzler48** [comment]
I’ll give it a test later and report back.
________________________________
