### ISSUE TITLE
[BUG] Closed caption Text missing

### ISSUE THREAD

**Issue by barbiehunter** [rbjaxter/budhud#545]
Closed captions seem to be some buggy looks like, I'm using `exec bh_captions` and Downloaded the Latest GitHub version 2 Days ago and problem still there.
![tf_win64_7aMA9c5q0W](https://github.com/user-attachments/assets/aa9deffd-f3f8-4895-865f-de160510f22d)
![tf_win64_6kClB1FbrZ](https://github.com/user-attachments/assets/35b616ee-7ed0-43ca-ac05-8e76c7894e69)
![tf_win64_7rGWzZEPM1](https://github.com/user-attachments/assets/af7349c6-213d-487b-91a2-1761b7e96757)

**Comment by rbjaxter** [comment]
The impression I'm getting is that closed captions are broken on all huds at the moment, but I need to look into it some more

**Comment by rbjaxter** [comment]
It seems like something to do with the `cc_subtitles` value may have changed, perhaps? Can you try using `exec bh_captions`, but then manually set `cc_subtitles` to 0? I honestly can't recall if this is what it used to look like, but it does generate text when you do this:
![image](https://github.com/user-attachments/assets/8e52b108-a343-4bc2-b2ba-0e698aa44399)

There are a lot of errors in console about it, though:
![image](https://github.com/user-attachments/assets/76f3c465-1dd5-4da5-a258-f4309d96abad)

**Comment by rbjaxter** [comment]
Worth noting, it seems like trying to regenerate the closed captions with the captioncompiler (`common/Team Fortress 2/bin`) seems to completely break the captions (more so than this).

It looks like it was updated October 22 2024, so I'm curious if whatever this update was is related to the issue:
<img width="860" alt="explorer_lnZxPmN6Jt" src="https://github.com/user-attachments/assets/7d156925-51ad-451b-b661-8d33e576ac6e">
