### ISSUE TITLE
new net_graph is broken on 1080p res with net_graphproportionalfont 0

### ISSUE THREAD

**Issue by vitalpulse** [rbjaxter/budhud#546]
![20241026010436_1](https://github.com/user-attachments/assets/68b577a7-6c04-41dd-8cb0-6615b35f00c6)

**Comment by truehighkey** [comment]
same issue persists with cl_showfps 1

![20241026010644_1](https://github.com/user-attachments/assets/f5552d81-c2a4-4d32-badd-fa302e19b7fc)

**Comment by rbjaxter** [comment]
net_graph & cl_showfps share a font entry, but only one can be proportionally controlled. even with `net_graphproportionalfont 0`, the behavior of net_graph is strange now. basically nothing can be done until either the TF team fixes it or someone figures out how their newly introduced values are supposed to be used

**Comment by truehighkey** [comment]
> net_graph & cl_showfps share a font entry, but only one can be proportionally controlled. even with `net_graphproportionalfont 0`, the behavior of net_graph is strange now. basically nothing can be done until either the TF team fixes it or someone figures out how their newly introduced values are supposed to be used

sucks to hear that, classic valve trying to fix something while breaking the other

**Comment by Liubik** [comment]
can confirm, I am having the same issue.
Using latest budhud release, Arch Linux.

**Comment by rbjaxter** [comment]
> I have no issues with `net_graph`, `cl_showpos`, or `cl_showfps` on 1080p using this setup: https://github.com/qkeitoe/budhud/blob/2e3bb9da3b149e4133b84cad627966c13bb1bae5/%23users/custom/resource/sourcescheme.res#L5-L17 ![Screenshot (92)](https://private-user-images.githubusercontent.com/66339491/387811479-bfa433f5-4fa4-47c7-9288-e6f5263dff71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMDk5NTEsIm5iZiI6MTczMjMwOTY1MSwicGF0aCI6Ii82NjMzOTQ5MS8zODc4MTE0NzktYmZhNDMzZjUtNGZhNC00N2M3LTkyODgtZTZmNTI2M2RmZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDIxMDczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MWVjNjY5ZGE1N2VmNzZlMmI0NGJjODQwODVmZjFkYTRmOTM3N2QyZGEyYmZjZDU4MjAzNjlhYzhiNmNiMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WddPtC3Jsj8ziN9Mm-Sx-yw0mu_uUSlFK6zeQ04c7J0)

This does work for 1920x1080, but on on the higher dpi resolutions unfortunately. I don't actually think there's a way to really have it work for both it seems

**Comment by rbjaxter** [comment]
I suppose that does make an improvement, but there are other issues relating to positioning/etc: (3840x2160):
![image](https://github.com/user-attachments/assets/571013cd-3e38-4fa1-a92d-93cff1d381ff)

I also had issues previously getting `isproportional` to work for this, but I'm wondering if I was just not testing it properly before..will need to see

**Comment by rbjaxter** [comment]
Whoops, sorry I think my github comment notifications are getting eaten or something

Here's 1920x1080 windowed noborder, 1920x1080 scaled up to 4k, and 4k:


![1920x1080 windowed noborder](https://github.com/user-attachments/assets/9af6b3d6-ee55-4513-aa0a-5c5cbac3f74c)
![1920x1080 fullscreen on 4k](https://github.com/user-attachments/assets/12383025-d1ec-4bbd-a1b7-f6612471b838)
![4k](https://github.com/user-attachments/assets/db15564d-0ea6-49b9-bbb9-a8687c4ce3b7)

**Comment by rbjaxter** [comment]
I think I've fixed this issue the best I can for now, at least on 1920x1080. I suppose we'll see, but let me know if there's anything else you're wondering about @qkeitoe

**Comment by rbjaxter** [comment]
Glad that it's working out :D more thanks goes to you for the values though of course
