### ISSUE TITLE
[Suggestion] Screenshot Previews for `#users` folder customizations

### ISSUE THREAD

**Issue by tekunotri** [rbjaxter/budhud#552]
i think the title is self-explanatory, maybe shouldn be somewhere in the imgur album or wiki page mostly for clarity

**Comment by rbjaxter** [comment]
The presets aren't really meant to be for people who aren't familiar already with what they look like, but I could probably at least take a screenshot of the in-game UI for each I suppose. Wouldn't hurt to flip through

**Comment by tekunotri** [comment]
i think a basic in-game screenshot would suffice imo

**Comment by rbjaxter** [comment]
added these to https://github.com/rbjaxter/budhud/wiki/YouTube-&-Twitch-User-HUDs

should cover the big ones

<img width="960" alt="tf_win64_U3t3kx4CBX" src="https://github.com/user-attachments/assets/2e2c1b80-fa1c-466e-bc02-0beaba4fa6ab">
<img width="960" alt="tf_win64_TCs3r7Zs6L" src="https://github.com/user-attachments/assets/429744fc-0ef3-4f55-aaec-1b83d5e85954">
<img width="960" alt="tf_win64_IBEAzS7o9J" src="https://github.com/user-attachments/assets/c0bd9810-b226-4371-9767-a6afb024043c">
