### ISSUE TITLE
TargetID Health Cross doesn't work.

### ISSUE THREAD

**Issue by Sizzler48** [rbjaxter/budhud#553]
![image](https://github.com/user-attachments/assets/9dfee423-a424-46bb-8753-a274538e4675)

**Comment by Sizzler48** [comment]
I did remove targetid depleting too.

**Comment by rbjaxter** [comment]
I know you said you removed it, but what you're seeing tends to happen with the depleting health customization enabled. It appears to be working on my end:
![image](https://github.com/user-attachments/assets/107655f5-0809-4276-b125-869fee4616fa)

(There is an issue with how it displays in the spy disguise however). Do you have something else enabled that I don't?
![image](https://github.com/user-attachments/assets/0bcbaedc-70d9-4546-95f2-37c496abd877)

**Comment by rbjaxter** [comment]
Let me know if you have any other information on what may be causing it. If you're able to reproduce it again, let me know what settings you're using/reopen the issue and I'll take another look

**Comment by Sizzler48** [comment]
Hi Jaxter,

Just tried again with a fresh HUD install (I jump around HUDS a lot) and works fine now! Not sure what went wrong my end.

Is it possible to alter the deathcam targetid (or include a new customisation) so that the health text is outside the health cross similar to the health cross customisation? I'm personally very picky about consistency lmao.
