### ISSUE TITLE
`bh_player_boxes` seems broken

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#556]
![image](https://github.com/user-attachments/assets/3a08f169-8d6b-4ff7-a4bd-263b54db1f33)

`hud_reloadscheme` fixes this though.

**Comment by rbjaxter** [comment]
Hmm interesting, hud_reloadscheme fixing it would suggest it has something to do with an animation but I don't believe I do any movement of it with animations. I wonder if it has something to do with using the cs values or something

**Comment by rbjaxter** [comment]
I've added a separate pin element and then pinned it to that, it seems to have resolved it from what I can tell..strange though
