### ISSUE TITLE
Fonts improvement suggestions

### ISSUE THREAD

**Issue by qkeitoe** [rbjaxter/budhud#560]
- Set a proper range for the Lato font entry, like [this](https://github.com/qkeitoe/budhud/blob/bd33d94a37898feb47d04205e5e2f661544e604f/%23users/custom/resource/clientscheme_custom.res#L75-L84) (Lato seems to support almost all characters within that range)
  Before:
  ![1](https://github.com/user-attachments/assets/4e45755a-f5b9-4938-8f04-8fe278f50648)
  After (it may be hard to see the difference, as Verdana is very similar to Lato):
  ![2](https://github.com/user-attachments/assets/b0400318-ec46-4871-b1b4-f9cd1b11bc2a)

- Replace some `SourceScheme` and `ChatScheme` fonts with Lato versions:

  - `UiBold` and `DefaultLarge` (don't seem to mess anything up)
  - `DefaultVerySmall`, `DefaultSmall`, `Default` (used everywhere, so unexpected problems can probably occur)
  - `ConsoleText` (I've heard from Hypnotize that it's better not to touch this one, because some ETF2L tool is (or at least used to be) only able to process information from user screenshots if the default font is used)
  - `ChatFont` (haven't noticed any problems, but not sure)

  If you're interested, I'll provide screenshots of where each is used (at least to my knowledge). Personally, I replaced all of the above fonts with Lato versions and I'm more than happy now :)

- Somehow improve the visibility of the font used by `HudHintDisplay`, since it looks kinda ugly even at 1080p. However, I have no idea what exact font definition is used there.
  ![image](https://github.com/user-attachments/assets/3cf7aa3a-7224-4a72-8923-9777bde8350c)

**Comment by rbjaxter** [comment]
I implemented a majority of those, I could probably add the achievement ones as well. In the past, I did actually change a few of those (such as chat font) to Lato but switched them back to default for one reason or another (might have been people complaining about it).

Regarding the jump timer, I **think** that's controlled by `HudHintText` in clientscheme. The actual element is `HudHintKeyDisplay`, and it's also animated to some extent. I vaguely remember trying to fix the appearance of it through animations, but I can't recall where I ended up with that. Its color is set by `FgColor` in clientscheme.res as well

**Comment by rbjaxter** [comment]
Agreed, it does look better that way. I'll also add it in for the next set of commits

**Comment by rbjaxter** [comment]
Interesting, it probably has to do with the way sourcescheme and sourceschemebase get squished together

**Comment by rbjaxter** [comment]
~~Interesting, I wonder why [Google Fonts](https://fonts.google.com/specimen/Lato/glyphs) doesn't list Russian in its glyphs whereas [Adobe does](https://fonts.adobe.com/fonts/lato#details-section+lato-hairline).~~

Ah, okay so it looks like Google Fonts is Lato 1.0, whereas Adobe Typekit is Lato 2.0 (3000+ glyphs). I think at some point (probably when I was doing the bot character font modifications) I downloaded the latest Lato..probably from his website. In any case, I think I have a better idea of which languages are actually supported by Lato now.

**Comment by rbjaxter** [comment]
@qkeitoe It sounds like I'd be needing to add this `0x0021 0x0513` range for anything using Lato, if I'm understanding right? And that ranges seems to cover Basic Latin, Latin-1 Supplement, Cyrillic and Cyrillic Supplement.

If I wanted to cover all the languages that Lato supports, I think the ranges would be:
0x0020–0x052F (Basic Latin, Latin Extended, Greek, Cyrillic)
0x2E80–0x9FFF (Chinese)
0xFE30–0xFE4F (CJK Compatibility)
0x2000–0x206F (Punctuation)

..the issue is that I'm not sure if you can list multiple ranges. I'm not sure where documentation exists for this. Maybe you can just list multiple `range` lines? I need to figure out how to test that 🤔

**Comment by rbjaxter** [comment]
> Btw, regarding [1d5960f](https://github.com/rbjaxter/budhud/commit/1d5960f0feacadb46460185be72eeb00e0dd6bee), I believe it's a good idea to do the same for `ChatScheme` and `SourceScheme` as well.

..strange, I never realized I didn't have CustomFontFiles defined for those. I suppose I didn't have Lato used before, though

**Comment by rbjaxter** [comment]
@qkeitoe Now that I think about it, I may have never changed the console font because Lato isn't monospaced: 
![image](https://github.com/user-attachments/assets/1d8e5a6f-54f1-4a92-b142-222f33860d70)

**Comment by rbjaxter** [comment]
No worries, it is your own take on the hud so you're free to do whatever you please with it :D. I do want to like Lato in the console, but the lack of monospacing is just really throwing me off unfortunately..

**Comment by rbjaxter** [comment]
I just forgot tbh, I need to add those ones in too

**Comment by rbjaxter** [comment]
Here's the achievement text updated:
before
<img width="311" alt="tf_win64_x9rwajjcF4" src="https://github.com/user-attachments/assets/f2610471-c0fa-40e2-b66b-42735b1e576a" />
after
<img width="311" alt="tf_win64_x9rwajjcF4" src="https://github.com/user-attachments/assets/b56ac407-5b30-48c1-ac67-935124e71ba5" />
