### ISSUE TITLE
when using baby face blaster on scout the boost meter never fills up all of the way

### ISSUE THREAD

**Issue by wahoo-man83** [rbjaxter/budhud#568]
when you fill up the boost meter all the way up to scout running at 520hu (the max bfb speed) the meter does not appear as full
i have 3 images
![20241220154234_1](https://github.com/user-attachments/assets/d91cde42-4e58-4abb-ab7e-f2fbe90c0822)
![20241220154158_1](https://github.com/user-attachments/assets/6e9ee835-8033-4cb1-8cf6-d88ac61f874e)
![20241220154147_1](https://github.com/user-attachments/assets/f3a5491c-f223-4522-88c2-ed6de8ec6346)

**Comment by rbjaxter** [comment]
Interestingly enough this does actually appear to happen in the default hud too (albeit on a smaller scale), so I'm actually not sure if there's anything I can really do about it:
![image](https://github.com/user-attachments/assets/f6f32cd0-d9ab-4c71-a255-942b87358bc5)
![image](https://github.com/user-attachments/assets/b6d5e374-9096-4cef-a487-9a99eb2bb320)

**Comment by rbjaxter** [comment]
I'm going to close this for now, but I did add it to the "Known Issues" under TF2 issues here for future reference: https://github.com/rbjaxter/budhud/wiki/Known-Issues
