### ISSUE TITLE
Chat covers achievement tracking

### ISSUE THREAD

**Issue by 50Wliu** [rbjaxter/budhud#79]
I'm probably the only one in the world that actually uses achievement tracking, so a quick description of what it does: you can turn on tracking for achievements within TF2, and then those achievements will show up on the upper-left hand side of your HUD when playing (with a progress bar if applicable).

Unfortunately, since the chat box is also in the upper-left corner, I can barely see anything.

![image](https://cloud.githubusercontent.com/assets/2766036/11172443/bce4c0dc-8bd5-11e5-95de-34d4d20788a6.png)

**Comment by WhiskerBiscuit** [comment]
I could try moving the achievement tracker down, but I'm worried it'll clip with the engineer hud. If you wanted to move the chat yourself so you could utilize that, all you need to do is go into `resource\ui\basechat.res` and adjust the xpos/ypos of the first entry ("HudChat")

**Comment by rbjaxter** [comment]
I've fixed this in the latest version of my hud; I haven't yet committed it, though.

**Comment by 50Wliu** [comment]
Awesome, thanks!
