### ISSUE TITLE
Drink + Soda Popper

### ISSUE THREAD

**Issue by TerminatorT800** [rbjaxter/budhud#86]
I don't have a picture on hand, but the charge meter for the drink (critacola/bonk) is covering most of the soda popper charge meter, leaving just a small red line indicating full charge

**Comment by rbjaxter** [comment]
That's intended, though I can't recall the specifics of why (I believe it clips with the TargetID or something of that nature)

**Comment by rbjaxter** [comment]
I actually decided to fix this in the latest version of my hud. Whenever I release the next update this will be fixed.

**Comment by TerminatorT800** [comment]
Thanks
