### ISSUE TITLE
War Progress Against budhud Rebellion

### ISSUE THREAD

**Issue by rbjaxter** [rbjaxter/budhud#96]
# War On Item Effect Meter Terror
Date: 10 February 2016 - present
Location: Realm of the budhud
## HUD Developer Belligerents:
Whisker of the budhud Nation
omnibombulator of the notohud Nation
## Item Effect Meter Belligerents:
**huditemeffectmeter**, Supreme Ruler of Weapon Meters
huditemeffectmeter_demoman of the Scottish Duchy
huditemeffectmeter_engineer of the Texas Duchy
huditemeffectmeter_scout of the Boston Duchy 
huditemeffectmeter_sniper of the New Zealand Duchy
huditemeffectmeter_spy of the French Duchy
huditemeffectmeter_cleaver of the Flying Guillotine County
huditemeffectmeter_killstreak of the Killstreak County
huditemeffectmeter_particlecannon of the Cow Mangling County
huditemeffectmeter_pomson of the Pomson County
huditemeffectmeter_powerupbottle of the Canteen County
huditemeffectmeter_raygun of the Righteous Bison County

**Comment by rbjaxter** [comment]
Update 1:  Omni of the Carrot Sovereignty has joined our cause to fight the effect meter hegemony. 
Update 2:  Plans have been drafted for the ultimate and assured destruction of pixel alignment belligerents.

**Comment by omnibombulator** [comment]
I totally did a thing to fight crime I think

**Comment by rbjaxter** [comment]
The supreme ruler of the huditemeffectmeter and all of his loyal supporters have been assimilated to the f0/f0 #base way of life. The only remaining belligerent standing is now the MvM medic shield.

**Comment by rbjaxter** [comment]
[The shield infidels have been routed ](http://i.imgur.com/jAYvTAp.jpg). The budhud War is dwindling to a close.

**Comment by rbjaxter** [comment]
All known belligerents have been terminated. The ItemEffectMeters shall be publicly terminated at the upcoming Commit Trials.
