### ISSUE TITLE
Missing Workshop option

### ISSUE THREAD

**Issue by SaintGamingston** [rbjaxter/budhud#97]
I can't seem to find the workshop anywhere in the start menu. It's getting annoying that I have to uninstall budhud everytime I wanna use the workshop.

Res: 2560x1440
OS: Windows 8.1

**Comment by rbjaxter** [comment]
Added in the next version of the hud, I'll close this when I commit the update. :)

**Comment by SaintGamingston** [comment]
Very nice !
